// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GMClientMessage.proto

package com.randioo.demo_optimisticframe_server.protocal.gm;

public final class GMClientMessage {
  private GMClientMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class GMCSMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use GMCSMessage.newBuilder() to construct.
    private GMCSMessage() {
      initFields();
    }
    private GMCSMessage(boolean noInit) {}
    
    private static final GMCSMessage defaultInstance;
    public static GMCSMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public GMCSMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.internal_static_com_randioo_demo_optimisticframe_server_protocal_gm_GMCSMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.internal_static_com_randioo_demo_optimisticframe_server_protocal_gm_GMCSMessage_fieldAccessorTable;
    }
    
    // optional int32 tag = 1 [default = 1];
    public static final int TAG_FIELD_NUMBER = 1;
    private boolean hasTag;
    private int tag_ = 1;
    public boolean hasTag() { return hasTag; }
    public int getTag() { return tag_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.gm.GmRejectLoginRequest gmRejectLoginRequest = 2;
    public static final int GMREJECTLOGINREQUEST_FIELD_NUMBER = 2;
    private boolean hasGmRejectLoginRequest;
    private com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmRejectLoginRequest gmRejectLoginRequest_;
    public boolean hasGmRejectLoginRequest() { return hasGmRejectLoginRequest; }
    public com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmRejectLoginRequest getGmRejectLoginRequest() { return gmRejectLoginRequest_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.gm.GmOpenLoginRequest gmOpenLoginRequest = 3;
    public static final int GMOPENLOGINREQUEST_FIELD_NUMBER = 3;
    private boolean hasGmOpenLoginRequest;
    private com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmOpenLoginRequest gmOpenLoginRequest_;
    public boolean hasGmOpenLoginRequest() { return hasGmOpenLoginRequest; }
    public com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmOpenLoginRequest getGmOpenLoginRequest() { return gmOpenLoginRequest_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.gm.GmShutdownServerRequest gmShutdownServerRequest = 4;
    public static final int GMSHUTDOWNSERVERREQUEST_FIELD_NUMBER = 4;
    private boolean hasGmShutdownServerRequest;
    private com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmShutdownServerRequest gmShutdownServerRequest_;
    public boolean hasGmShutdownServerRequest() { return hasGmShutdownServerRequest; }
    public com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmShutdownServerRequest getGmShutdownServerRequest() { return gmShutdownServerRequest_; }
    
    private void initFields() {
      gmRejectLoginRequest_ = com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmRejectLoginRequest.getDefaultInstance();
      gmOpenLoginRequest_ = com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmOpenLoginRequest.getDefaultInstance();
      gmShutdownServerRequest_ = com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmShutdownServerRequest.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasTag()) {
        output.writeInt32(1, getTag());
      }
      if (hasGmRejectLoginRequest()) {
        output.writeMessage(2, getGmRejectLoginRequest());
      }
      if (hasGmOpenLoginRequest()) {
        output.writeMessage(3, getGmOpenLoginRequest());
      }
      if (hasGmShutdownServerRequest()) {
        output.writeMessage(4, getGmShutdownServerRequest());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTag()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getTag());
      }
      if (hasGmRejectLoginRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getGmRejectLoginRequest());
      }
      if (hasGmOpenLoginRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getGmOpenLoginRequest());
      }
      if (hasGmShutdownServerRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getGmShutdownServerRequest());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage result;
      
      // Construct using com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage();
        return builder;
      }
      
      protected com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage.getDescriptor();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage getDefaultInstanceForType() {
        return com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage) {
          return mergeFrom((com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage other) {
        if (other == com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage.getDefaultInstance()) return this;
        if (other.hasTag()) {
          setTag(other.getTag());
        }
        if (other.hasGmRejectLoginRequest()) {
          mergeGmRejectLoginRequest(other.getGmRejectLoginRequest());
        }
        if (other.hasGmOpenLoginRequest()) {
          mergeGmOpenLoginRequest(other.getGmOpenLoginRequest());
        }
        if (other.hasGmShutdownServerRequest()) {
          mergeGmShutdownServerRequest(other.getGmShutdownServerRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setTag(input.readInt32());
              break;
            }
            case 18: {
              com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmRejectLoginRequest.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmRejectLoginRequest.newBuilder();
              if (hasGmRejectLoginRequest()) {
                subBuilder.mergeFrom(getGmRejectLoginRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGmRejectLoginRequest(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmOpenLoginRequest.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmOpenLoginRequest.newBuilder();
              if (hasGmOpenLoginRequest()) {
                subBuilder.mergeFrom(getGmOpenLoginRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGmOpenLoginRequest(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmShutdownServerRequest.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmShutdownServerRequest.newBuilder();
              if (hasGmShutdownServerRequest()) {
                subBuilder.mergeFrom(getGmShutdownServerRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGmShutdownServerRequest(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional int32 tag = 1 [default = 1];
      public boolean hasTag() {
        return result.hasTag();
      }
      public int getTag() {
        return result.getTag();
      }
      public Builder setTag(int value) {
        result.hasTag = true;
        result.tag_ = value;
        return this;
      }
      public Builder clearTag() {
        result.hasTag = false;
        result.tag_ = 1;
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.gm.GmRejectLoginRequest gmRejectLoginRequest = 2;
      public boolean hasGmRejectLoginRequest() {
        return result.hasGmRejectLoginRequest();
      }
      public com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmRejectLoginRequest getGmRejectLoginRequest() {
        return result.getGmRejectLoginRequest();
      }
      public Builder setGmRejectLoginRequest(com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmRejectLoginRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGmRejectLoginRequest = true;
        result.gmRejectLoginRequest_ = value;
        return this;
      }
      public Builder setGmRejectLoginRequest(com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmRejectLoginRequest.Builder builderForValue) {
        result.hasGmRejectLoginRequest = true;
        result.gmRejectLoginRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeGmRejectLoginRequest(com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmRejectLoginRequest value) {
        if (result.hasGmRejectLoginRequest() &&
            result.gmRejectLoginRequest_ != com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmRejectLoginRequest.getDefaultInstance()) {
          result.gmRejectLoginRequest_ =
            com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmRejectLoginRequest.newBuilder(result.gmRejectLoginRequest_).mergeFrom(value).buildPartial();
        } else {
          result.gmRejectLoginRequest_ = value;
        }
        result.hasGmRejectLoginRequest = true;
        return this;
      }
      public Builder clearGmRejectLoginRequest() {
        result.hasGmRejectLoginRequest = false;
        result.gmRejectLoginRequest_ = com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmRejectLoginRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.gm.GmOpenLoginRequest gmOpenLoginRequest = 3;
      public boolean hasGmOpenLoginRequest() {
        return result.hasGmOpenLoginRequest();
      }
      public com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmOpenLoginRequest getGmOpenLoginRequest() {
        return result.getGmOpenLoginRequest();
      }
      public Builder setGmOpenLoginRequest(com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmOpenLoginRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGmOpenLoginRequest = true;
        result.gmOpenLoginRequest_ = value;
        return this;
      }
      public Builder setGmOpenLoginRequest(com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmOpenLoginRequest.Builder builderForValue) {
        result.hasGmOpenLoginRequest = true;
        result.gmOpenLoginRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeGmOpenLoginRequest(com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmOpenLoginRequest value) {
        if (result.hasGmOpenLoginRequest() &&
            result.gmOpenLoginRequest_ != com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmOpenLoginRequest.getDefaultInstance()) {
          result.gmOpenLoginRequest_ =
            com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmOpenLoginRequest.newBuilder(result.gmOpenLoginRequest_).mergeFrom(value).buildPartial();
        } else {
          result.gmOpenLoginRequest_ = value;
        }
        result.hasGmOpenLoginRequest = true;
        return this;
      }
      public Builder clearGmOpenLoginRequest() {
        result.hasGmOpenLoginRequest = false;
        result.gmOpenLoginRequest_ = com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmOpenLoginRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.gm.GmShutdownServerRequest gmShutdownServerRequest = 4;
      public boolean hasGmShutdownServerRequest() {
        return result.hasGmShutdownServerRequest();
      }
      public com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmShutdownServerRequest getGmShutdownServerRequest() {
        return result.getGmShutdownServerRequest();
      }
      public Builder setGmShutdownServerRequest(com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmShutdownServerRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGmShutdownServerRequest = true;
        result.gmShutdownServerRequest_ = value;
        return this;
      }
      public Builder setGmShutdownServerRequest(com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmShutdownServerRequest.Builder builderForValue) {
        result.hasGmShutdownServerRequest = true;
        result.gmShutdownServerRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeGmShutdownServerRequest(com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmShutdownServerRequest value) {
        if (result.hasGmShutdownServerRequest() &&
            result.gmShutdownServerRequest_ != com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmShutdownServerRequest.getDefaultInstance()) {
          result.gmShutdownServerRequest_ =
            com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmShutdownServerRequest.newBuilder(result.gmShutdownServerRequest_).mergeFrom(value).buildPartial();
        } else {
          result.gmShutdownServerRequest_ = value;
        }
        result.hasGmShutdownServerRequest = true;
        return this;
      }
      public Builder clearGmShutdownServerRequest() {
        result.hasGmShutdownServerRequest = false;
        result.gmShutdownServerRequest_ = com.randioo.demo_optimisticframe_server.protocal.gm.GM.GmShutdownServerRequest.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.demo_optimisticframe_server.protocal.gm.GMCSMessage)
    }
    
    static {
      defaultInstance = new GMCSMessage(true);
      com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.demo_optimisticframe_server.protocal.gm.GMCSMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_demo_optimisticframe_server_protocal_gm_GMCSMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_demo_optimisticframe_server_protocal_gm_GMCSMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025GMClientMessage.proto\0223com.randioo.dem" +
      "o_optimisticframe_server.protocal.gm\032\010GM" +
      ".proto\"\332\002\n\013GMCSMessage\022\016\n\003tag\030\001 \001(\005:\0011\022g" +
      "\n\024gmRejectLoginRequest\030\002 \001(\0132I.com.randi" +
      "oo.demo_optimisticframe_server.protocal." +
      "gm.GmRejectLoginRequest\022c\n\022gmOpenLoginRe" +
      "quest\030\003 \001(\0132G.com.randioo.demo_optimisti" +
      "cframe_server.protocal.gm.GmOpenLoginReq" +
      "uest\022m\n\027gmShutdownServerRequest\030\004 \001(\0132L." +
      "com.randioo.demo_optimisticframe_server.",
      "protocal.gm.GmShutdownServerRequest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_demo_optimisticframe_server_protocal_gm_GMCSMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_gm_GMCSMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_demo_optimisticframe_server_protocal_gm_GMCSMessage_descriptor,
              new java.lang.String[] { "Tag", "GmRejectLoginRequest", "GmOpenLoginRequest", "GmShutdownServerRequest", },
              com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage.class,
              com.randioo.demo_optimisticframe_server.protocal.gm.GMClientMessage.GMCSMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.demo_optimisticframe_server.protocal.gm.GM.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
