// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessage.proto

package com.randioo.demo_optimisticframe_server.protocal;

public final class ClientMessage {
  private ClientMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CSMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use CSMessage.newBuilder() to construct.
    private CSMessage() {
      initFields();
    }
    private CSMessage(boolean noInit) {}
    
    private static final CSMessage defaultInstance;
    public static CSMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public CSMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.demo_optimisticframe_server.protocal.ClientMessage.internal_static_com_randioo_demo_optimisticframe_server_protocal_CSMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.demo_optimisticframe_server.protocal.ClientMessage.internal_static_com_randioo_demo_optimisticframe_server_protocal_CSMessage_fieldAccessorTable;
    }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.LoginCheckAccountRequest loginCheckAccountRequest = 1;
    public static final int LOGINCHECKACCOUNTREQUEST_FIELD_NUMBER = 1;
    private boolean hasLoginCheckAccountRequest;
    private com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountRequest loginCheckAccountRequest_;
    public boolean hasLoginCheckAccountRequest() { return hasLoginCheckAccountRequest; }
    public com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountRequest getLoginCheckAccountRequest() { return loginCheckAccountRequest_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.LoginCreateRoleRequest loginCreateRoleRequest = 2;
    public static final int LOGINCREATEROLEREQUEST_FIELD_NUMBER = 2;
    private boolean hasLoginCreateRoleRequest;
    private com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleRequest loginCreateRoleRequest_;
    public boolean hasLoginCreateRoleRequest() { return hasLoginCreateRoleRequest; }
    public com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleRequest getLoginCreateRoleRequest() { return loginCreateRoleRequest_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.LoginGetRoleDataRequest loginGetRoleDataRequest = 3;
    public static final int LOGINGETROLEDATAREQUEST_FIELD_NUMBER = 3;
    private boolean hasLoginGetRoleDataRequest;
    private com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataRequest loginGetRoleDataRequest_;
    public boolean hasLoginGetRoleDataRequest() { return hasLoginGetRoleDataRequest; }
    public com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataRequest getLoginGetRoleDataRequest() { return loginGetRoleDataRequest_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.MatchRoleRequest matchRoleRequest = 4;
    public static final int MATCHROLEREQUEST_FIELD_NUMBER = 4;
    private boolean hasMatchRoleRequest;
    private com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleRequest matchRoleRequest_;
    public boolean hasMatchRoleRequest() { return hasMatchRoleRequest; }
    public com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleRequest getMatchRoleRequest() { return matchRoleRequest_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.FightReceiveHitGameControlRequest fightReceiveHitGameControlRequest = 5;
    public static final int FIGHTRECEIVEHITGAMECONTROLREQUEST_FIELD_NUMBER = 5;
    private boolean hasFightReceiveHitGameControlRequest;
    private com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlRequest fightReceiveHitGameControlRequest_;
    public boolean hasFightReceiveHitGameControlRequest() { return hasFightReceiveHitGameControlRequest; }
    public com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlRequest getFightReceiveHitGameControlRequest() { return fightReceiveHitGameControlRequest_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.FightReceivePlaneGameControlRequest fightReceivePlaneGameControlRequest = 6;
    public static final int FIGHTRECEIVEPLANEGAMECONTROLREQUEST_FIELD_NUMBER = 6;
    private boolean hasFightReceivePlaneGameControlRequest;
    private com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlRequest fightReceivePlaneGameControlRequest_;
    public boolean hasFightReceivePlaneGameControlRequest() { return hasFightReceivePlaneGameControlRequest; }
    public com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlRequest getFightReceivePlaneGameControlRequest() { return fightReceivePlaneGameControlRequest_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.FightLoadCompleteRequest fightLoadCompleteRequest = 7;
    public static final int FIGHTLOADCOMPLETEREQUEST_FIELD_NUMBER = 7;
    private boolean hasFightLoadCompleteRequest;
    private com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteRequest fightLoadCompleteRequest_;
    public boolean hasFightLoadCompleteRequest() { return hasFightLoadCompleteRequest; }
    public com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteRequest getFightLoadCompleteRequest() { return fightLoadCompleteRequest_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.PingRequest pingRequest = 8;
    public static final int PINGREQUEST_FIELD_NUMBER = 8;
    private boolean hasPingRequest;
    private com.randioo.demo_optimisticframe_server.protocal.Ping.PingRequest pingRequest_;
    public boolean hasPingRequest() { return hasPingRequest; }
    public com.randioo.demo_optimisticframe_server.protocal.Ping.PingRequest getPingRequest() { return pingRequest_; }
    
    private void initFields() {
      loginCheckAccountRequest_ = com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountRequest.getDefaultInstance();
      loginCreateRoleRequest_ = com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleRequest.getDefaultInstance();
      loginGetRoleDataRequest_ = com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataRequest.getDefaultInstance();
      matchRoleRequest_ = com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleRequest.getDefaultInstance();
      fightReceiveHitGameControlRequest_ = com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlRequest.getDefaultInstance();
      fightReceivePlaneGameControlRequest_ = com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlRequest.getDefaultInstance();
      fightLoadCompleteRequest_ = com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteRequest.getDefaultInstance();
      pingRequest_ = com.randioo.demo_optimisticframe_server.protocal.Ping.PingRequest.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasLoginCheckAccountRequest()) {
        output.writeMessage(1, getLoginCheckAccountRequest());
      }
      if (hasLoginCreateRoleRequest()) {
        output.writeMessage(2, getLoginCreateRoleRequest());
      }
      if (hasLoginGetRoleDataRequest()) {
        output.writeMessage(3, getLoginGetRoleDataRequest());
      }
      if (hasMatchRoleRequest()) {
        output.writeMessage(4, getMatchRoleRequest());
      }
      if (hasFightReceiveHitGameControlRequest()) {
        output.writeMessage(5, getFightReceiveHitGameControlRequest());
      }
      if (hasFightReceivePlaneGameControlRequest()) {
        output.writeMessage(6, getFightReceivePlaneGameControlRequest());
      }
      if (hasFightLoadCompleteRequest()) {
        output.writeMessage(7, getFightLoadCompleteRequest());
      }
      if (hasPingRequest()) {
        output.writeMessage(8, getPingRequest());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasLoginCheckAccountRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLoginCheckAccountRequest());
      }
      if (hasLoginCreateRoleRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLoginCreateRoleRequest());
      }
      if (hasLoginGetRoleDataRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLoginGetRoleDataRequest());
      }
      if (hasMatchRoleRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getMatchRoleRequest());
      }
      if (hasFightReceiveHitGameControlRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getFightReceiveHitGameControlRequest());
      }
      if (hasFightReceivePlaneGameControlRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getFightReceivePlaneGameControlRequest());
      }
      if (hasFightLoadCompleteRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getFightLoadCompleteRequest());
      }
      if (hasPingRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getPingRequest());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage result;
      
      // Construct using com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage();
        return builder;
      }
      
      protected com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage.getDescriptor();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage getDefaultInstanceForType() {
        return com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage) {
          return mergeFrom((com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage other) {
        if (other == com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage.getDefaultInstance()) return this;
        if (other.hasLoginCheckAccountRequest()) {
          mergeLoginCheckAccountRequest(other.getLoginCheckAccountRequest());
        }
        if (other.hasLoginCreateRoleRequest()) {
          mergeLoginCreateRoleRequest(other.getLoginCreateRoleRequest());
        }
        if (other.hasLoginGetRoleDataRequest()) {
          mergeLoginGetRoleDataRequest(other.getLoginGetRoleDataRequest());
        }
        if (other.hasMatchRoleRequest()) {
          mergeMatchRoleRequest(other.getMatchRoleRequest());
        }
        if (other.hasFightReceiveHitGameControlRequest()) {
          mergeFightReceiveHitGameControlRequest(other.getFightReceiveHitGameControlRequest());
        }
        if (other.hasFightReceivePlaneGameControlRequest()) {
          mergeFightReceivePlaneGameControlRequest(other.getFightReceivePlaneGameControlRequest());
        }
        if (other.hasFightLoadCompleteRequest()) {
          mergeFightLoadCompleteRequest(other.getFightLoadCompleteRequest());
        }
        if (other.hasPingRequest()) {
          mergePingRequest(other.getPingRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountRequest.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountRequest.newBuilder();
              if (hasLoginCheckAccountRequest()) {
                subBuilder.mergeFrom(getLoginCheckAccountRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCheckAccountRequest(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleRequest.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleRequest.newBuilder();
              if (hasLoginCreateRoleRequest()) {
                subBuilder.mergeFrom(getLoginCreateRoleRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCreateRoleRequest(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataRequest.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataRequest.newBuilder();
              if (hasLoginGetRoleDataRequest()) {
                subBuilder.mergeFrom(getLoginGetRoleDataRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginGetRoleDataRequest(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleRequest.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleRequest.newBuilder();
              if (hasMatchRoleRequest()) {
                subBuilder.mergeFrom(getMatchRoleRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMatchRoleRequest(subBuilder.buildPartial());
              break;
            }
            case 42: {
              com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlRequest.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlRequest.newBuilder();
              if (hasFightReceiveHitGameControlRequest()) {
                subBuilder.mergeFrom(getFightReceiveHitGameControlRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFightReceiveHitGameControlRequest(subBuilder.buildPartial());
              break;
            }
            case 50: {
              com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlRequest.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlRequest.newBuilder();
              if (hasFightReceivePlaneGameControlRequest()) {
                subBuilder.mergeFrom(getFightReceivePlaneGameControlRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFightReceivePlaneGameControlRequest(subBuilder.buildPartial());
              break;
            }
            case 58: {
              com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteRequest.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteRequest.newBuilder();
              if (hasFightLoadCompleteRequest()) {
                subBuilder.mergeFrom(getFightLoadCompleteRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFightLoadCompleteRequest(subBuilder.buildPartial());
              break;
            }
            case 66: {
              com.randioo.demo_optimisticframe_server.protocal.Ping.PingRequest.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Ping.PingRequest.newBuilder();
              if (hasPingRequest()) {
                subBuilder.mergeFrom(getPingRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPingRequest(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.LoginCheckAccountRequest loginCheckAccountRequest = 1;
      public boolean hasLoginCheckAccountRequest() {
        return result.hasLoginCheckAccountRequest();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountRequest getLoginCheckAccountRequest() {
        return result.getLoginCheckAccountRequest();
      }
      public Builder setLoginCheckAccountRequest(com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCheckAccountRequest = true;
        result.loginCheckAccountRequest_ = value;
        return this;
      }
      public Builder setLoginCheckAccountRequest(com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountRequest.Builder builderForValue) {
        result.hasLoginCheckAccountRequest = true;
        result.loginCheckAccountRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCheckAccountRequest(com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountRequest value) {
        if (result.hasLoginCheckAccountRequest() &&
            result.loginCheckAccountRequest_ != com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountRequest.getDefaultInstance()) {
          result.loginCheckAccountRequest_ =
            com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountRequest.newBuilder(result.loginCheckAccountRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginCheckAccountRequest_ = value;
        }
        result.hasLoginCheckAccountRequest = true;
        return this;
      }
      public Builder clearLoginCheckAccountRequest() {
        result.hasLoginCheckAccountRequest = false;
        result.loginCheckAccountRequest_ = com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.LoginCreateRoleRequest loginCreateRoleRequest = 2;
      public boolean hasLoginCreateRoleRequest() {
        return result.hasLoginCreateRoleRequest();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleRequest getLoginCreateRoleRequest() {
        return result.getLoginCreateRoleRequest();
      }
      public Builder setLoginCreateRoleRequest(com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCreateRoleRequest = true;
        result.loginCreateRoleRequest_ = value;
        return this;
      }
      public Builder setLoginCreateRoleRequest(com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleRequest.Builder builderForValue) {
        result.hasLoginCreateRoleRequest = true;
        result.loginCreateRoleRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCreateRoleRequest(com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleRequest value) {
        if (result.hasLoginCreateRoleRequest() &&
            result.loginCreateRoleRequest_ != com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleRequest.getDefaultInstance()) {
          result.loginCreateRoleRequest_ =
            com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleRequest.newBuilder(result.loginCreateRoleRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginCreateRoleRequest_ = value;
        }
        result.hasLoginCreateRoleRequest = true;
        return this;
      }
      public Builder clearLoginCreateRoleRequest() {
        result.hasLoginCreateRoleRequest = false;
        result.loginCreateRoleRequest_ = com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.LoginGetRoleDataRequest loginGetRoleDataRequest = 3;
      public boolean hasLoginGetRoleDataRequest() {
        return result.hasLoginGetRoleDataRequest();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataRequest getLoginGetRoleDataRequest() {
        return result.getLoginGetRoleDataRequest();
      }
      public Builder setLoginGetRoleDataRequest(com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginGetRoleDataRequest = true;
        result.loginGetRoleDataRequest_ = value;
        return this;
      }
      public Builder setLoginGetRoleDataRequest(com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataRequest.Builder builderForValue) {
        result.hasLoginGetRoleDataRequest = true;
        result.loginGetRoleDataRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginGetRoleDataRequest(com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataRequest value) {
        if (result.hasLoginGetRoleDataRequest() &&
            result.loginGetRoleDataRequest_ != com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataRequest.getDefaultInstance()) {
          result.loginGetRoleDataRequest_ =
            com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataRequest.newBuilder(result.loginGetRoleDataRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginGetRoleDataRequest_ = value;
        }
        result.hasLoginGetRoleDataRequest = true;
        return this;
      }
      public Builder clearLoginGetRoleDataRequest() {
        result.hasLoginGetRoleDataRequest = false;
        result.loginGetRoleDataRequest_ = com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.MatchRoleRequest matchRoleRequest = 4;
      public boolean hasMatchRoleRequest() {
        return result.hasMatchRoleRequest();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleRequest getMatchRoleRequest() {
        return result.getMatchRoleRequest();
      }
      public Builder setMatchRoleRequest(com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasMatchRoleRequest = true;
        result.matchRoleRequest_ = value;
        return this;
      }
      public Builder setMatchRoleRequest(com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleRequest.Builder builderForValue) {
        result.hasMatchRoleRequest = true;
        result.matchRoleRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeMatchRoleRequest(com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleRequest value) {
        if (result.hasMatchRoleRequest() &&
            result.matchRoleRequest_ != com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleRequest.getDefaultInstance()) {
          result.matchRoleRequest_ =
            com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleRequest.newBuilder(result.matchRoleRequest_).mergeFrom(value).buildPartial();
        } else {
          result.matchRoleRequest_ = value;
        }
        result.hasMatchRoleRequest = true;
        return this;
      }
      public Builder clearMatchRoleRequest() {
        result.hasMatchRoleRequest = false;
        result.matchRoleRequest_ = com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.FightReceiveHitGameControlRequest fightReceiveHitGameControlRequest = 5;
      public boolean hasFightReceiveHitGameControlRequest() {
        return result.hasFightReceiveHitGameControlRequest();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlRequest getFightReceiveHitGameControlRequest() {
        return result.getFightReceiveHitGameControlRequest();
      }
      public Builder setFightReceiveHitGameControlRequest(com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFightReceiveHitGameControlRequest = true;
        result.fightReceiveHitGameControlRequest_ = value;
        return this;
      }
      public Builder setFightReceiveHitGameControlRequest(com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlRequest.Builder builderForValue) {
        result.hasFightReceiveHitGameControlRequest = true;
        result.fightReceiveHitGameControlRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeFightReceiveHitGameControlRequest(com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlRequest value) {
        if (result.hasFightReceiveHitGameControlRequest() &&
            result.fightReceiveHitGameControlRequest_ != com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlRequest.getDefaultInstance()) {
          result.fightReceiveHitGameControlRequest_ =
            com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlRequest.newBuilder(result.fightReceiveHitGameControlRequest_).mergeFrom(value).buildPartial();
        } else {
          result.fightReceiveHitGameControlRequest_ = value;
        }
        result.hasFightReceiveHitGameControlRequest = true;
        return this;
      }
      public Builder clearFightReceiveHitGameControlRequest() {
        result.hasFightReceiveHitGameControlRequest = false;
        result.fightReceiveHitGameControlRequest_ = com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.FightReceivePlaneGameControlRequest fightReceivePlaneGameControlRequest = 6;
      public boolean hasFightReceivePlaneGameControlRequest() {
        return result.hasFightReceivePlaneGameControlRequest();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlRequest getFightReceivePlaneGameControlRequest() {
        return result.getFightReceivePlaneGameControlRequest();
      }
      public Builder setFightReceivePlaneGameControlRequest(com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFightReceivePlaneGameControlRequest = true;
        result.fightReceivePlaneGameControlRequest_ = value;
        return this;
      }
      public Builder setFightReceivePlaneGameControlRequest(com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlRequest.Builder builderForValue) {
        result.hasFightReceivePlaneGameControlRequest = true;
        result.fightReceivePlaneGameControlRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeFightReceivePlaneGameControlRequest(com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlRequest value) {
        if (result.hasFightReceivePlaneGameControlRequest() &&
            result.fightReceivePlaneGameControlRequest_ != com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlRequest.getDefaultInstance()) {
          result.fightReceivePlaneGameControlRequest_ =
            com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlRequest.newBuilder(result.fightReceivePlaneGameControlRequest_).mergeFrom(value).buildPartial();
        } else {
          result.fightReceivePlaneGameControlRequest_ = value;
        }
        result.hasFightReceivePlaneGameControlRequest = true;
        return this;
      }
      public Builder clearFightReceivePlaneGameControlRequest() {
        result.hasFightReceivePlaneGameControlRequest = false;
        result.fightReceivePlaneGameControlRequest_ = com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.FightLoadCompleteRequest fightLoadCompleteRequest = 7;
      public boolean hasFightLoadCompleteRequest() {
        return result.hasFightLoadCompleteRequest();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteRequest getFightLoadCompleteRequest() {
        return result.getFightLoadCompleteRequest();
      }
      public Builder setFightLoadCompleteRequest(com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFightLoadCompleteRequest = true;
        result.fightLoadCompleteRequest_ = value;
        return this;
      }
      public Builder setFightLoadCompleteRequest(com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteRequest.Builder builderForValue) {
        result.hasFightLoadCompleteRequest = true;
        result.fightLoadCompleteRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeFightLoadCompleteRequest(com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteRequest value) {
        if (result.hasFightLoadCompleteRequest() &&
            result.fightLoadCompleteRequest_ != com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteRequest.getDefaultInstance()) {
          result.fightLoadCompleteRequest_ =
            com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteRequest.newBuilder(result.fightLoadCompleteRequest_).mergeFrom(value).buildPartial();
        } else {
          result.fightLoadCompleteRequest_ = value;
        }
        result.hasFightLoadCompleteRequest = true;
        return this;
      }
      public Builder clearFightLoadCompleteRequest() {
        result.hasFightLoadCompleteRequest = false;
        result.fightLoadCompleteRequest_ = com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.PingRequest pingRequest = 8;
      public boolean hasPingRequest() {
        return result.hasPingRequest();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Ping.PingRequest getPingRequest() {
        return result.getPingRequest();
      }
      public Builder setPingRequest(com.randioo.demo_optimisticframe_server.protocal.Ping.PingRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPingRequest = true;
        result.pingRequest_ = value;
        return this;
      }
      public Builder setPingRequest(com.randioo.demo_optimisticframe_server.protocal.Ping.PingRequest.Builder builderForValue) {
        result.hasPingRequest = true;
        result.pingRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergePingRequest(com.randioo.demo_optimisticframe_server.protocal.Ping.PingRequest value) {
        if (result.hasPingRequest() &&
            result.pingRequest_ != com.randioo.demo_optimisticframe_server.protocal.Ping.PingRequest.getDefaultInstance()) {
          result.pingRequest_ =
            com.randioo.demo_optimisticframe_server.protocal.Ping.PingRequest.newBuilder(result.pingRequest_).mergeFrom(value).buildPartial();
        } else {
          result.pingRequest_ = value;
        }
        result.hasPingRequest = true;
        return this;
      }
      public Builder clearPingRequest() {
        result.hasPingRequest = false;
        result.pingRequest_ = com.randioo.demo_optimisticframe_server.protocal.Ping.PingRequest.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.demo_optimisticframe_server.protocal.CSMessage)
    }
    
    static {
      defaultInstance = new CSMessage(true);
      com.randioo.demo_optimisticframe_server.protocal.ClientMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.demo_optimisticframe_server.protocal.CSMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_demo_optimisticframe_server_protocal_CSMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_demo_optimisticframe_server_protocal_CSMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ClientMessage.proto\0220com.randioo.demo_" +
      "optimisticframe_server.protocal\032\013Login.p" +
      "roto\032\013Match.proto\032\013Fight.proto\032\nPing.pro" +
      "to\"\364\006\n\tCSMessage\022l\n\030loginCheckAccountReq" +
      "uest\030\001 \001(\0132J.com.randioo.demo_optimistic" +
      "frame_server.protocal.LoginCheckAccountR" +
      "equest\022h\n\026loginCreateRoleRequest\030\002 \001(\0132H" +
      ".com.randioo.demo_optimisticframe_server" +
      ".protocal.LoginCreateRoleRequest\022j\n\027logi" +
      "nGetRoleDataRequest\030\003 \001(\0132I.com.randioo.",
      "demo_optimisticframe_server.protocal.Log" +
      "inGetRoleDataRequest\022\\\n\020matchRoleRequest" +
      "\030\004 \001(\0132B.com.randioo.demo_optimisticfram" +
      "e_server.protocal.MatchRoleRequest\022~\n!fi" +
      "ghtReceiveHitGameControlRequest\030\005 \001(\0132S." +
      "com.randioo.demo_optimisticframe_server." +
      "protocal.FightReceiveHitGameControlReque" +
      "st\022\202\001\n#fightReceivePlaneGameControlReque" +
      "st\030\006 \001(\0132U.com.randioo.demo_optimisticfr" +
      "ame_server.protocal.FightReceivePlaneGam",
      "eControlRequest\022l\n\030fightLoadCompleteRequ" +
      "est\030\007 \001(\0132J.com.randioo.demo_optimisticf" +
      "rame_server.protocal.FightLoadCompleteRe" +
      "quest\022R\n\013pingRequest\030\010 \001(\0132=.com.randioo" +
      ".demo_optimisticframe_server.protocal.Pi" +
      "ngRequest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_demo_optimisticframe_server_protocal_CSMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_CSMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_demo_optimisticframe_server_protocal_CSMessage_descriptor,
              new java.lang.String[] { "LoginCheckAccountRequest", "LoginCreateRoleRequest", "LoginGetRoleDataRequest", "MatchRoleRequest", "FightReceiveHitGameControlRequest", "FightReceivePlaneGameControlRequest", "FightLoadCompleteRequest", "PingRequest", },
              com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage.class,
              com.randioo.demo_optimisticframe_server.protocal.ClientMessage.CSMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.demo_optimisticframe_server.protocal.Login.getDescriptor(),
          com.randioo.demo_optimisticframe_server.protocal.Match.getDescriptor(),
          com.randioo.demo_optimisticframe_server.protocal.Fight.getDescriptor(),
          com.randioo.demo_optimisticframe_server.protocal.Ping.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
