// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Invite.proto

package com.randioo.demo_optimisticframe_server.protocal;

public final class Invite {
  private Invite() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class InviteFriendRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use InviteFriendRequest.newBuilder() to construct.
    private InviteFriendRequest() {
      initFields();
    }
    private InviteFriendRequest(boolean noInit) {}
    
    private static final InviteFriendRequest defaultInstance;
    public static InviteFriendRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public InviteFriendRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.demo_optimisticframe_server.protocal.Invite.internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteFriendRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.demo_optimisticframe_server.protocal.Invite.internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteFriendRequest_fieldAccessorTable;
    }
    
    // optional string account = 1;
    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private boolean hasAccount;
    private java.lang.String account_ = "";
    public boolean hasAccount() { return hasAccount; }
    public java.lang.String getAccount() { return account_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasAccount()) {
        output.writeString(1, getAccount());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasAccount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getAccount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest result;
      
      // Construct using com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest();
        return builder;
      }
      
      protected com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest.getDescriptor();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest getDefaultInstanceForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest) {
          return mergeFrom((com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest other) {
        if (other == com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest.getDefaultInstance()) return this;
        if (other.hasAccount()) {
          setAccount(other.getAccount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setAccount(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string account = 1;
      public boolean hasAccount() {
        return result.hasAccount();
      }
      public java.lang.String getAccount() {
        return result.getAccount();
      }
      public Builder setAccount(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAccount = true;
        result.account_ = value;
        return this;
      }
      public Builder clearAccount() {
        result.hasAccount = false;
        result.account_ = getDefaultInstance().getAccount();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.demo_optimisticframe_server.protocal.InviteFriendRequest)
    }
    
    static {
      defaultInstance = new InviteFriendRequest(true);
      com.randioo.demo_optimisticframe_server.protocal.Invite.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.demo_optimisticframe_server.protocal.InviteFriendRequest)
  }
  
  public static final class InviteFriendResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use InviteFriendResponse.newBuilder() to construct.
    private InviteFriendResponse() {
      initFields();
    }
    private InviteFriendResponse(boolean noInit) {}
    
    private static final InviteFriendResponse defaultInstance;
    public static InviteFriendResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public InviteFriendResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.demo_optimisticframe_server.protocal.Invite.internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteFriendResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.demo_optimisticframe_server.protocal.Invite.internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteFriendResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1;
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 0;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse result;
      
      // Construct using com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse();
        return builder;
      }
      
      protected com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse.getDescriptor();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse getDefaultInstanceForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse) {
          return mergeFrom((com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse other) {
        if (other == com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1;
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.demo_optimisticframe_server.protocal.InviteFriendResponse)
    }
    
    static {
      defaultInstance = new InviteFriendResponse(true);
      com.randioo.demo_optimisticframe_server.protocal.Invite.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.demo_optimisticframe_server.protocal.InviteFriendResponse)
  }
  
  public static final class InviteAnswerRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use InviteAnswerRequest.newBuilder() to construct.
    private InviteAnswerRequest() {
      initFields();
    }
    private InviteAnswerRequest(boolean noInit) {}
    
    private static final InviteAnswerRequest defaultInstance;
    public static InviteAnswerRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public InviteAnswerRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.demo_optimisticframe_server.protocal.Invite.internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteAnswerRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.demo_optimisticframe_server.protocal.Invite.internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteAnswerRequest_fieldAccessorTable;
    }
    
    // optional string account = 1;
    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private boolean hasAccount;
    private java.lang.String account_ = "";
    public boolean hasAccount() { return hasAccount; }
    public java.lang.String getAccount() { return account_; }
    
    // optional bool answer = 2;
    public static final int ANSWER_FIELD_NUMBER = 2;
    private boolean hasAnswer;
    private boolean answer_ = false;
    public boolean hasAnswer() { return hasAnswer; }
    public boolean getAnswer() { return answer_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasAccount()) {
        output.writeString(1, getAccount());
      }
      if (hasAnswer()) {
        output.writeBool(2, getAnswer());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasAccount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getAccount());
      }
      if (hasAnswer()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, getAnswer());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest result;
      
      // Construct using com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest();
        return builder;
      }
      
      protected com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest.getDescriptor();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest getDefaultInstanceForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest) {
          return mergeFrom((com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest other) {
        if (other == com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest.getDefaultInstance()) return this;
        if (other.hasAccount()) {
          setAccount(other.getAccount());
        }
        if (other.hasAnswer()) {
          setAnswer(other.getAnswer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setAccount(input.readString());
              break;
            }
            case 16: {
              setAnswer(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // optional string account = 1;
      public boolean hasAccount() {
        return result.hasAccount();
      }
      public java.lang.String getAccount() {
        return result.getAccount();
      }
      public Builder setAccount(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAccount = true;
        result.account_ = value;
        return this;
      }
      public Builder clearAccount() {
        result.hasAccount = false;
        result.account_ = getDefaultInstance().getAccount();
        return this;
      }
      
      // optional bool answer = 2;
      public boolean hasAnswer() {
        return result.hasAnswer();
      }
      public boolean getAnswer() {
        return result.getAnswer();
      }
      public Builder setAnswer(boolean value) {
        result.hasAnswer = true;
        result.answer_ = value;
        return this;
      }
      public Builder clearAnswer() {
        result.hasAnswer = false;
        result.answer_ = false;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.demo_optimisticframe_server.protocal.InviteAnswerRequest)
    }
    
    static {
      defaultInstance = new InviteAnswerRequest(true);
      com.randioo.demo_optimisticframe_server.protocal.Invite.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.demo_optimisticframe_server.protocal.InviteAnswerRequest)
  }
  
  public static final class InviteAnswerResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use InviteAnswerResponse.newBuilder() to construct.
    private InviteAnswerResponse() {
      initFields();
    }
    private InviteAnswerResponse(boolean noInit) {}
    
    private static final InviteAnswerResponse defaultInstance;
    public static InviteAnswerResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public InviteAnswerResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.demo_optimisticframe_server.protocal.Invite.internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteAnswerResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.demo_optimisticframe_server.protocal.Invite.internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteAnswerResponse_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse result;
      
      // Construct using com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse();
        return builder;
      }
      
      protected com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse.getDescriptor();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse getDefaultInstanceForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse) {
          return mergeFrom((com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse other) {
        if (other == com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.demo_optimisticframe_server.protocal.InviteAnswerResponse)
    }
    
    static {
      defaultInstance = new InviteAnswerResponse(true);
      com.randioo.demo_optimisticframe_server.protocal.Invite.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.demo_optimisticframe_server.protocal.InviteAnswerResponse)
  }
  
  public static final class SCInviteAccept extends
      com.google.protobuf.GeneratedMessage {
    // Use SCInviteAccept.newBuilder() to construct.
    private SCInviteAccept() {
      initFields();
    }
    private SCInviteAccept(boolean noInit) {}
    
    private static final SCInviteAccept defaultInstance;
    public static SCInviteAccept getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCInviteAccept getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.demo_optimisticframe_server.protocal.Invite.internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteAccept_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.demo_optimisticframe_server.protocal.Invite.internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteAccept_fieldAccessorTable;
    }
    
    // optional string starter = 1;
    public static final int STARTER_FIELD_NUMBER = 1;
    private boolean hasStarter;
    private java.lang.String starter_ = "";
    public boolean hasStarter() { return hasStarter; }
    public java.lang.String getStarter() { return starter_; }
    
    // optional string targeter = 2;
    public static final int TARGETER_FIELD_NUMBER = 2;
    private boolean hasTargeter;
    private java.lang.String targeter_ = "";
    public boolean hasTargeter() { return hasTargeter; }
    public java.lang.String getTargeter() { return targeter_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasStarter()) {
        output.writeString(1, getStarter());
      }
      if (hasTargeter()) {
        output.writeString(2, getTargeter());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasStarter()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getStarter());
      }
      if (hasTargeter()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getTargeter());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept result;
      
      // Construct using com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept();
        return builder;
      }
      
      protected com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept.getDescriptor();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept getDefaultInstanceForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept) {
          return mergeFrom((com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept other) {
        if (other == com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept.getDefaultInstance()) return this;
        if (other.hasStarter()) {
          setStarter(other.getStarter());
        }
        if (other.hasTargeter()) {
          setTargeter(other.getTargeter());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setStarter(input.readString());
              break;
            }
            case 18: {
              setTargeter(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string starter = 1;
      public boolean hasStarter() {
        return result.hasStarter();
      }
      public java.lang.String getStarter() {
        return result.getStarter();
      }
      public Builder setStarter(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasStarter = true;
        result.starter_ = value;
        return this;
      }
      public Builder clearStarter() {
        result.hasStarter = false;
        result.starter_ = getDefaultInstance().getStarter();
        return this;
      }
      
      // optional string targeter = 2;
      public boolean hasTargeter() {
        return result.hasTargeter();
      }
      public java.lang.String getTargeter() {
        return result.getTargeter();
      }
      public Builder setTargeter(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTargeter = true;
        result.targeter_ = value;
        return this;
      }
      public Builder clearTargeter() {
        result.hasTargeter = false;
        result.targeter_ = getDefaultInstance().getTargeter();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.demo_optimisticframe_server.protocal.SCInviteAccept)
    }
    
    static {
      defaultInstance = new SCInviteAccept(true);
      com.randioo.demo_optimisticframe_server.protocal.Invite.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.demo_optimisticframe_server.protocal.SCInviteAccept)
  }
  
  public static final class SCInviteReject extends
      com.google.protobuf.GeneratedMessage {
    // Use SCInviteReject.newBuilder() to construct.
    private SCInviteReject() {
      initFields();
    }
    private SCInviteReject(boolean noInit) {}
    
    private static final SCInviteReject defaultInstance;
    public static SCInviteReject getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCInviteReject getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.demo_optimisticframe_server.protocal.Invite.internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteReject_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.demo_optimisticframe_server.protocal.Invite.internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteReject_fieldAccessorTable;
    }
    
    // optional string starter = 1;
    public static final int STARTER_FIELD_NUMBER = 1;
    private boolean hasStarter;
    private java.lang.String starter_ = "";
    public boolean hasStarter() { return hasStarter; }
    public java.lang.String getStarter() { return starter_; }
    
    // optional string targeter = 2;
    public static final int TARGETER_FIELD_NUMBER = 2;
    private boolean hasTargeter;
    private java.lang.String targeter_ = "";
    public boolean hasTargeter() { return hasTargeter; }
    public java.lang.String getTargeter() { return targeter_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasStarter()) {
        output.writeString(1, getStarter());
      }
      if (hasTargeter()) {
        output.writeString(2, getTargeter());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasStarter()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getStarter());
      }
      if (hasTargeter()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getTargeter());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject result;
      
      // Construct using com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject();
        return builder;
      }
      
      protected com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject.getDescriptor();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject getDefaultInstanceForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject) {
          return mergeFrom((com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject other) {
        if (other == com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject.getDefaultInstance()) return this;
        if (other.hasStarter()) {
          setStarter(other.getStarter());
        }
        if (other.hasTargeter()) {
          setTargeter(other.getTargeter());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setStarter(input.readString());
              break;
            }
            case 18: {
              setTargeter(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string starter = 1;
      public boolean hasStarter() {
        return result.hasStarter();
      }
      public java.lang.String getStarter() {
        return result.getStarter();
      }
      public Builder setStarter(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasStarter = true;
        result.starter_ = value;
        return this;
      }
      public Builder clearStarter() {
        result.hasStarter = false;
        result.starter_ = getDefaultInstance().getStarter();
        return this;
      }
      
      // optional string targeter = 2;
      public boolean hasTargeter() {
        return result.hasTargeter();
      }
      public java.lang.String getTargeter() {
        return result.getTargeter();
      }
      public Builder setTargeter(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTargeter = true;
        result.targeter_ = value;
        return this;
      }
      public Builder clearTargeter() {
        result.hasTargeter = false;
        result.targeter_ = getDefaultInstance().getTargeter();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.demo_optimisticframe_server.protocal.SCInviteReject)
    }
    
    static {
      defaultInstance = new SCInviteReject(true);
      com.randioo.demo_optimisticframe_server.protocal.Invite.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.demo_optimisticframe_server.protocal.SCInviteReject)
  }
  
  public static final class SCInviteCancel extends
      com.google.protobuf.GeneratedMessage {
    // Use SCInviteCancel.newBuilder() to construct.
    private SCInviteCancel() {
      initFields();
    }
    private SCInviteCancel(boolean noInit) {}
    
    private static final SCInviteCancel defaultInstance;
    public static SCInviteCancel getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCInviteCancel getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.demo_optimisticframe_server.protocal.Invite.internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteCancel_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.demo_optimisticframe_server.protocal.Invite.internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteCancel_fieldAccessorTable;
    }
    
    // optional string starter = 1;
    public static final int STARTER_FIELD_NUMBER = 1;
    private boolean hasStarter;
    private java.lang.String starter_ = "";
    public boolean hasStarter() { return hasStarter; }
    public java.lang.String getStarter() { return starter_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasStarter()) {
        output.writeString(1, getStarter());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasStarter()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getStarter());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel result;
      
      // Construct using com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel();
        return builder;
      }
      
      protected com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel.getDescriptor();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel getDefaultInstanceForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel) {
          return mergeFrom((com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel other) {
        if (other == com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel.getDefaultInstance()) return this;
        if (other.hasStarter()) {
          setStarter(other.getStarter());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setStarter(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string starter = 1;
      public boolean hasStarter() {
        return result.hasStarter();
      }
      public java.lang.String getStarter() {
        return result.getStarter();
      }
      public Builder setStarter(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasStarter = true;
        result.starter_ = value;
        return this;
      }
      public Builder clearStarter() {
        result.hasStarter = false;
        result.starter_ = getDefaultInstance().getStarter();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.demo_optimisticframe_server.protocal.SCInviteCancel)
    }
    
    static {
      defaultInstance = new SCInviteCancel(true);
      com.randioo.demo_optimisticframe_server.protocal.Invite.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.demo_optimisticframe_server.protocal.SCInviteCancel)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteFriendRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteFriendRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteFriendResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteFriendResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteAnswerRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteAnswerRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteAnswerResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteAnswerResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteAccept_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteAccept_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteReject_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteReject_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteCancel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteCancel_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Invite.proto\0220com.randioo.demo_optimis" +
      "ticframe_server.protocal\"&\n\023InviteFriend" +
      "Request\022\017\n\007account\030\001 \001(\t\")\n\024InviteFriend" +
      "Response\022\021\n\terrorCode\030\001 \001(\005\"6\n\023InviteAns" +
      "werRequest\022\017\n\007account\030\001 \001(\t\022\016\n\006answer\030\002 " +
      "\001(\010\"\026\n\024InviteAnswerResponse\"3\n\016SCInviteA" +
      "ccept\022\017\n\007starter\030\001 \001(\t\022\020\n\010targeter\030\002 \001(\t" +
      "\"3\n\016SCInviteReject\022\017\n\007starter\030\001 \001(\t\022\020\n\010t" +
      "argeter\030\002 \001(\t\"!\n\016SCInviteCancel\022\017\n\007start" +
      "er\030\001 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteFriendRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteFriendRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteFriendRequest_descriptor,
              new java.lang.String[] { "Account", },
              com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest.class,
              com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendRequest.Builder.class);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteFriendResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteFriendResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteFriendResponse_descriptor,
              new java.lang.String[] { "ErrorCode", },
              com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse.class,
              com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse.Builder.class);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteAnswerRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteAnswerRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteAnswerRequest_descriptor,
              new java.lang.String[] { "Account", "Answer", },
              com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest.class,
              com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerRequest.Builder.class);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteAnswerResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteAnswerResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_demo_optimisticframe_server_protocal_InviteAnswerResponse_descriptor,
              new java.lang.String[] { },
              com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse.class,
              com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse.Builder.class);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteAccept_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteAccept_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteAccept_descriptor,
              new java.lang.String[] { "Starter", "Targeter", },
              com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept.class,
              com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept.Builder.class);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteReject_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteReject_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteReject_descriptor,
              new java.lang.String[] { "Starter", "Targeter", },
              com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject.class,
              com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject.Builder.class);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteCancel_descriptor =
            getDescriptor().getMessageTypes().get(6);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteCancel_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_demo_optimisticframe_server_protocal_SCInviteCancel_descriptor,
              new java.lang.String[] { "Starter", },
              com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel.class,
              com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
