// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Role.proto

package com.randioo.demo_optimisticframe_server.protocal;

public final class Role {
  private Role() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class RoleChoosePlaneRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use RoleChoosePlaneRequest.newBuilder() to construct.
    private RoleChoosePlaneRequest() {
      initFields();
    }
    private RoleChoosePlaneRequest(boolean noInit) {}
    
    private static final RoleChoosePlaneRequest defaultInstance;
    public static RoleChoosePlaneRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoleChoosePlaneRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.demo_optimisticframe_server.protocal.Role.internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleChoosePlaneRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.demo_optimisticframe_server.protocal.Role.internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleChoosePlaneRequest_fieldAccessorTable;
    }
    
    // optional int32 planeId = 1;
    public static final int PLANEID_FIELD_NUMBER = 1;
    private boolean hasPlaneId;
    private int planeId_ = 0;
    public boolean hasPlaneId() { return hasPlaneId; }
    public int getPlaneId() { return planeId_; }
    
    // optional int32 index = 2;
    public static final int INDEX_FIELD_NUMBER = 2;
    private boolean hasIndex;
    private int index_ = 0;
    public boolean hasIndex() { return hasIndex; }
    public int getIndex() { return index_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasPlaneId()) {
        output.writeInt32(1, getPlaneId());
      }
      if (hasIndex()) {
        output.writeInt32(2, getIndex());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasPlaneId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getPlaneId());
      }
      if (hasIndex()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getIndex());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest result;
      
      // Construct using com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest();
        return builder;
      }
      
      protected com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest.getDescriptor();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest getDefaultInstanceForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest) {
          return mergeFrom((com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest other) {
        if (other == com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest.getDefaultInstance()) return this;
        if (other.hasPlaneId()) {
          setPlaneId(other.getPlaneId());
        }
        if (other.hasIndex()) {
          setIndex(other.getIndex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setPlaneId(input.readInt32());
              break;
            }
            case 16: {
              setIndex(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 planeId = 1;
      public boolean hasPlaneId() {
        return result.hasPlaneId();
      }
      public int getPlaneId() {
        return result.getPlaneId();
      }
      public Builder setPlaneId(int value) {
        result.hasPlaneId = true;
        result.planeId_ = value;
        return this;
      }
      public Builder clearPlaneId() {
        result.hasPlaneId = false;
        result.planeId_ = 0;
        return this;
      }
      
      // optional int32 index = 2;
      public boolean hasIndex() {
        return result.hasIndex();
      }
      public int getIndex() {
        return result.getIndex();
      }
      public Builder setIndex(int value) {
        result.hasIndex = true;
        result.index_ = value;
        return this;
      }
      public Builder clearIndex() {
        result.hasIndex = false;
        result.index_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.demo_optimisticframe_server.protocal.RoleChoosePlaneRequest)
    }
    
    static {
      defaultInstance = new RoleChoosePlaneRequest(true);
      com.randioo.demo_optimisticframe_server.protocal.Role.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.demo_optimisticframe_server.protocal.RoleChoosePlaneRequest)
  }
  
  public static final class RoleChoosePlaneResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use RoleChoosePlaneResponse.newBuilder() to construct.
    private RoleChoosePlaneResponse() {
      initFields();
    }
    private RoleChoosePlaneResponse(boolean noInit) {}
    
    private static final RoleChoosePlaneResponse defaultInstance;
    public static RoleChoosePlaneResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoleChoosePlaneResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.demo_optimisticframe_server.protocal.Role.internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleChoosePlaneResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.demo_optimisticframe_server.protocal.Role.internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleChoosePlaneResponse_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse result;
      
      // Construct using com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse();
        return builder;
      }
      
      protected com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse.getDescriptor();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse getDefaultInstanceForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse) {
          return mergeFrom((com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse other) {
        if (other == com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.demo_optimisticframe_server.protocal.RoleChoosePlaneResponse)
    }
    
    static {
      defaultInstance = new RoleChoosePlaneResponse(true);
      com.randioo.demo_optimisticframe_server.protocal.Role.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.demo_optimisticframe_server.protocal.RoleChoosePlaneResponse)
  }
  
  public static final class RoleFallPlaneRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use RoleFallPlaneRequest.newBuilder() to construct.
    private RoleFallPlaneRequest() {
      initFields();
    }
    private RoleFallPlaneRequest(boolean noInit) {}
    
    private static final RoleFallPlaneRequest defaultInstance;
    public static RoleFallPlaneRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoleFallPlaneRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.demo_optimisticframe_server.protocal.Role.internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleFallPlaneRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.demo_optimisticframe_server.protocal.Role.internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleFallPlaneRequest_fieldAccessorTable;
    }
    
    // optional int32 index = 1;
    public static final int INDEX_FIELD_NUMBER = 1;
    private boolean hasIndex;
    private int index_ = 0;
    public boolean hasIndex() { return hasIndex; }
    public int getIndex() { return index_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasIndex()) {
        output.writeInt32(1, getIndex());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasIndex()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getIndex());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest result;
      
      // Construct using com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest();
        return builder;
      }
      
      protected com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest.getDescriptor();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest getDefaultInstanceForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest) {
          return mergeFrom((com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest other) {
        if (other == com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest.getDefaultInstance()) return this;
        if (other.hasIndex()) {
          setIndex(other.getIndex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setIndex(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 index = 1;
      public boolean hasIndex() {
        return result.hasIndex();
      }
      public int getIndex() {
        return result.getIndex();
      }
      public Builder setIndex(int value) {
        result.hasIndex = true;
        result.index_ = value;
        return this;
      }
      public Builder clearIndex() {
        result.hasIndex = false;
        result.index_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.demo_optimisticframe_server.protocal.RoleFallPlaneRequest)
    }
    
    static {
      defaultInstance = new RoleFallPlaneRequest(true);
      com.randioo.demo_optimisticframe_server.protocal.Role.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.demo_optimisticframe_server.protocal.RoleFallPlaneRequest)
  }
  
  public static final class RoleFallPlaneResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use RoleFallPlaneResponse.newBuilder() to construct.
    private RoleFallPlaneResponse() {
      initFields();
    }
    private RoleFallPlaneResponse(boolean noInit) {}
    
    private static final RoleFallPlaneResponse defaultInstance;
    public static RoleFallPlaneResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoleFallPlaneResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.demo_optimisticframe_server.protocal.Role.internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleFallPlaneResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.demo_optimisticframe_server.protocal.Role.internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleFallPlaneResponse_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse result;
      
      // Construct using com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse();
        return builder;
      }
      
      protected com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse.getDescriptor();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse getDefaultInstanceForType() {
        return com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse) {
          return mergeFrom((com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse other) {
        if (other == com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.demo_optimisticframe_server.protocal.RoleFallPlaneResponse)
    }
    
    static {
      defaultInstance = new RoleFallPlaneResponse(true);
      com.randioo.demo_optimisticframe_server.protocal.Role.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.demo_optimisticframe_server.protocal.RoleFallPlaneResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleChoosePlaneRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleChoosePlaneRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleChoosePlaneResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleChoosePlaneResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleFallPlaneRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleFallPlaneRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleFallPlaneResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleFallPlaneResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nRole.proto\0220com.randioo.demo_optimisti" +
      "cframe_server.protocal\"8\n\026RoleChoosePlan" +
      "eRequest\022\017\n\007planeId\030\001 \001(\005\022\r\n\005index\030\002 \001(\005" +
      "\"\031\n\027RoleChoosePlaneResponse\"%\n\024RoleFallP" +
      "laneRequest\022\r\n\005index\030\001 \001(\005\"\027\n\025RoleFallPl" +
      "aneResponse"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleChoosePlaneRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleChoosePlaneRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleChoosePlaneRequest_descriptor,
              new java.lang.String[] { "PlaneId", "Index", },
              com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest.class,
              com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneRequest.Builder.class);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleChoosePlaneResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleChoosePlaneResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleChoosePlaneResponse_descriptor,
              new java.lang.String[] { },
              com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse.class,
              com.randioo.demo_optimisticframe_server.protocal.Role.RoleChoosePlaneResponse.Builder.class);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleFallPlaneRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleFallPlaneRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleFallPlaneRequest_descriptor,
              new java.lang.String[] { "Index", },
              com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest.class,
              com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneRequest.Builder.class);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleFallPlaneResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleFallPlaneResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_demo_optimisticframe_server_protocal_RoleFallPlaneResponse_descriptor,
              new java.lang.String[] { },
              com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse.class,
              com.randioo.demo_optimisticframe_server.protocal.Role.RoleFallPlaneResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
