// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerMessage.proto

package com.randioo.demo_optimisticframe_server.protocal;

public final class ServerMessage {
  private ServerMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class SCMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use SCMessage.newBuilder() to construct.
    private SCMessage() {
      initFields();
    }
    private SCMessage(boolean noInit) {}
    
    private static final SCMessage defaultInstance;
    public static SCMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.demo_optimisticframe_server.protocal.ServerMessage.internal_static_com_randioo_demo_optimisticframe_server_protocal_SCMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.demo_optimisticframe_server.protocal.ServerMessage.internal_static_com_randioo_demo_optimisticframe_server_protocal_SCMessage_fieldAccessorTable;
    }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.LoginCheckAccountResponse loginCheckAccountResponse = 1;
    public static final int LOGINCHECKACCOUNTRESPONSE_FIELD_NUMBER = 1;
    private boolean hasLoginCheckAccountResponse;
    private com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountResponse loginCheckAccountResponse_;
    public boolean hasLoginCheckAccountResponse() { return hasLoginCheckAccountResponse; }
    public com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountResponse getLoginCheckAccountResponse() { return loginCheckAccountResponse_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.LoginCreateRoleResponse loginCreateRoleResponse = 2;
    public static final int LOGINCREATEROLERESPONSE_FIELD_NUMBER = 2;
    private boolean hasLoginCreateRoleResponse;
    private com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleResponse loginCreateRoleResponse_;
    public boolean hasLoginCreateRoleResponse() { return hasLoginCreateRoleResponse; }
    public com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleResponse getLoginCreateRoleResponse() { return loginCreateRoleResponse_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.LoginGetRoleDataResponse loginGetRoleDataResponse = 3;
    public static final int LOGINGETROLEDATARESPONSE_FIELD_NUMBER = 3;
    private boolean hasLoginGetRoleDataResponse;
    private com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataResponse loginGetRoleDataResponse_;
    public boolean hasLoginGetRoleDataResponse() { return hasLoginGetRoleDataResponse; }
    public com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataResponse getLoginGetRoleDataResponse() { return loginGetRoleDataResponse_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.MatchRoleResponse matchRoleResponse = 4;
    public static final int MATCHROLERESPONSE_FIELD_NUMBER = 4;
    private boolean hasMatchRoleResponse;
    private com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleResponse matchRoleResponse_;
    public boolean hasMatchRoleResponse() { return hasMatchRoleResponse; }
    public com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleResponse getMatchRoleResponse() { return matchRoleResponse_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.FightReceiveHitGameControlResponse fightReceiveHitGameControlResponse = 5;
    public static final int FIGHTRECEIVEHITGAMECONTROLRESPONSE_FIELD_NUMBER = 5;
    private boolean hasFightReceiveHitGameControlResponse;
    private com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlResponse fightReceiveHitGameControlResponse_;
    public boolean hasFightReceiveHitGameControlResponse() { return hasFightReceiveHitGameControlResponse; }
    public com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlResponse getFightReceiveHitGameControlResponse() { return fightReceiveHitGameControlResponse_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.FightReceivePlaneGameControlResponse fightReceivePlaneGameControlResponse = 6;
    public static final int FIGHTRECEIVEPLANEGAMECONTROLRESPONSE_FIELD_NUMBER = 6;
    private boolean hasFightReceivePlaneGameControlResponse;
    private com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlResponse fightReceivePlaneGameControlResponse_;
    public boolean hasFightReceivePlaneGameControlResponse() { return hasFightReceivePlaneGameControlResponse; }
    public com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlResponse getFightReceivePlaneGameControlResponse() { return fightReceivePlaneGameControlResponse_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.FightLoadCompleteResponse fightLoadCompleteResponse = 7;
    public static final int FIGHTLOADCOMPLETERESPONSE_FIELD_NUMBER = 7;
    private boolean hasFightLoadCompleteResponse;
    private com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteResponse fightLoadCompleteResponse_;
    public boolean hasFightLoadCompleteResponse() { return hasFightLoadCompleteResponse; }
    public com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteResponse getFightLoadCompleteResponse() { return fightLoadCompleteResponse_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.SCFightStartGame scFightStartGame = 8;
    public static final int SCFIGHTSTARTGAME_FIELD_NUMBER = 8;
    private boolean hasScFightStartGame;
    private com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightStartGame scFightStartGame_;
    public boolean hasScFightStartGame() { return hasScFightStartGame; }
    public com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightStartGame getScFightStartGame() { return scFightStartGame_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.SCFightLoadResource scFightLoadResource = 9;
    public static final int SCFIGHTLOADRESOURCE_FIELD_NUMBER = 9;
    private boolean hasScFightLoadResource;
    private com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightLoadResource scFightLoadResource_;
    public boolean hasScFightLoadResource() { return hasScFightLoadResource; }
    public com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightLoadResource getScFightLoadResource() { return scFightLoadResource_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.SCFightRemove scFightRemove = 10;
    public static final int SCFIGHTREMOVE_FIELD_NUMBER = 10;
    private boolean hasScFightRemove;
    private com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightRemove scFightRemove_;
    public boolean hasScFightRemove() { return hasScFightRemove; }
    public com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightRemove getScFightRemove() { return scFightRemove_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.SCFightCreate scFightCreate = 11;
    public static final int SCFIGHTCREATE_FIELD_NUMBER = 11;
    private boolean hasScFightCreate;
    private com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightCreate scFightCreate_;
    public boolean hasScFightCreate() { return hasScFightCreate; }
    public com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightCreate getScFightCreate() { return scFightCreate_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.SCFightGameOver scFightGameOver = 12;
    public static final int SCFIGHTGAMEOVER_FIELD_NUMBER = 12;
    private boolean hasScFightGameOver;
    private com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightGameOver scFightGameOver_;
    public boolean hasScFightGameOver() { return hasScFightGameOver; }
    public com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightGameOver getScFightGameOver() { return scFightGameOver_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.SCFightSendKeyFrame scFightSendKeyFrame = 13;
    public static final int SCFIGHTSENDKEYFRAME_FIELD_NUMBER = 13;
    private boolean hasScFightSendKeyFrame;
    private com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightSendKeyFrame scFightSendKeyFrame_;
    public boolean hasScFightSendKeyFrame() { return hasScFightSendKeyFrame; }
    public com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightSendKeyFrame getScFightSendKeyFrame() { return scFightSendKeyFrame_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.PingResponse pingResponse = 14;
    public static final int PINGRESPONSE_FIELD_NUMBER = 14;
    private boolean hasPingResponse;
    private com.randioo.demo_optimisticframe_server.protocal.Ping.PingResponse pingResponse_;
    public boolean hasPingResponse() { return hasPingResponse; }
    public com.randioo.demo_optimisticframe_server.protocal.Ping.PingResponse getPingResponse() { return pingResponse_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.InviteFriendResponse inviteFriendResponse = 15;
    public static final int INVITEFRIENDRESPONSE_FIELD_NUMBER = 15;
    private boolean hasInviteFriendResponse;
    private com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse inviteFriendResponse_;
    public boolean hasInviteFriendResponse() { return hasInviteFriendResponse; }
    public com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse getInviteFriendResponse() { return inviteFriendResponse_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.InviteAnswerResponse inviteAnswerResponse = 16;
    public static final int INVITEANSWERRESPONSE_FIELD_NUMBER = 16;
    private boolean hasInviteAnswerResponse;
    private com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse inviteAnswerResponse_;
    public boolean hasInviteAnswerResponse() { return hasInviteAnswerResponse; }
    public com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse getInviteAnswerResponse() { return inviteAnswerResponse_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.SCInviteAccept scInviteAccept = 17;
    public static final int SCINVITEACCEPT_FIELD_NUMBER = 17;
    private boolean hasScInviteAccept;
    private com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept scInviteAccept_;
    public boolean hasScInviteAccept() { return hasScInviteAccept; }
    public com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept getScInviteAccept() { return scInviteAccept_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.SCInviteReject scInviteReject = 18;
    public static final int SCINVITEREJECT_FIELD_NUMBER = 18;
    private boolean hasScInviteReject;
    private com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject scInviteReject_;
    public boolean hasScInviteReject() { return hasScInviteReject; }
    public com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject getScInviteReject() { return scInviteReject_; }
    
    // optional .com.randioo.demo_optimisticframe_server.protocal.SCInviteCancel scInviteCancel = 19;
    public static final int SCINVITECANCEL_FIELD_NUMBER = 19;
    private boolean hasScInviteCancel;
    private com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel scInviteCancel_;
    public boolean hasScInviteCancel() { return hasScInviteCancel; }
    public com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel getScInviteCancel() { return scInviteCancel_; }
    
    private void initFields() {
      loginCheckAccountResponse_ = com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountResponse.getDefaultInstance();
      loginCreateRoleResponse_ = com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleResponse.getDefaultInstance();
      loginGetRoleDataResponse_ = com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataResponse.getDefaultInstance();
      matchRoleResponse_ = com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleResponse.getDefaultInstance();
      fightReceiveHitGameControlResponse_ = com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlResponse.getDefaultInstance();
      fightReceivePlaneGameControlResponse_ = com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlResponse.getDefaultInstance();
      fightLoadCompleteResponse_ = com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteResponse.getDefaultInstance();
      scFightStartGame_ = com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightStartGame.getDefaultInstance();
      scFightLoadResource_ = com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightLoadResource.getDefaultInstance();
      scFightRemove_ = com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightRemove.getDefaultInstance();
      scFightCreate_ = com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightCreate.getDefaultInstance();
      scFightGameOver_ = com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightGameOver.getDefaultInstance();
      scFightSendKeyFrame_ = com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightSendKeyFrame.getDefaultInstance();
      pingResponse_ = com.randioo.demo_optimisticframe_server.protocal.Ping.PingResponse.getDefaultInstance();
      inviteFriendResponse_ = com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse.getDefaultInstance();
      inviteAnswerResponse_ = com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse.getDefaultInstance();
      scInviteAccept_ = com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept.getDefaultInstance();
      scInviteReject_ = com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject.getDefaultInstance();
      scInviteCancel_ = com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasLoginCheckAccountResponse()) {
        output.writeMessage(1, getLoginCheckAccountResponse());
      }
      if (hasLoginCreateRoleResponse()) {
        output.writeMessage(2, getLoginCreateRoleResponse());
      }
      if (hasLoginGetRoleDataResponse()) {
        output.writeMessage(3, getLoginGetRoleDataResponse());
      }
      if (hasMatchRoleResponse()) {
        output.writeMessage(4, getMatchRoleResponse());
      }
      if (hasFightReceiveHitGameControlResponse()) {
        output.writeMessage(5, getFightReceiveHitGameControlResponse());
      }
      if (hasFightReceivePlaneGameControlResponse()) {
        output.writeMessage(6, getFightReceivePlaneGameControlResponse());
      }
      if (hasFightLoadCompleteResponse()) {
        output.writeMessage(7, getFightLoadCompleteResponse());
      }
      if (hasScFightStartGame()) {
        output.writeMessage(8, getScFightStartGame());
      }
      if (hasScFightLoadResource()) {
        output.writeMessage(9, getScFightLoadResource());
      }
      if (hasScFightRemove()) {
        output.writeMessage(10, getScFightRemove());
      }
      if (hasScFightCreate()) {
        output.writeMessage(11, getScFightCreate());
      }
      if (hasScFightGameOver()) {
        output.writeMessage(12, getScFightGameOver());
      }
      if (hasScFightSendKeyFrame()) {
        output.writeMessage(13, getScFightSendKeyFrame());
      }
      if (hasPingResponse()) {
        output.writeMessage(14, getPingResponse());
      }
      if (hasInviteFriendResponse()) {
        output.writeMessage(15, getInviteFriendResponse());
      }
      if (hasInviteAnswerResponse()) {
        output.writeMessage(16, getInviteAnswerResponse());
      }
      if (hasScInviteAccept()) {
        output.writeMessage(17, getScInviteAccept());
      }
      if (hasScInviteReject()) {
        output.writeMessage(18, getScInviteReject());
      }
      if (hasScInviteCancel()) {
        output.writeMessage(19, getScInviteCancel());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasLoginCheckAccountResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLoginCheckAccountResponse());
      }
      if (hasLoginCreateRoleResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLoginCreateRoleResponse());
      }
      if (hasLoginGetRoleDataResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLoginGetRoleDataResponse());
      }
      if (hasMatchRoleResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getMatchRoleResponse());
      }
      if (hasFightReceiveHitGameControlResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getFightReceiveHitGameControlResponse());
      }
      if (hasFightReceivePlaneGameControlResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getFightReceivePlaneGameControlResponse());
      }
      if (hasFightLoadCompleteResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getFightLoadCompleteResponse());
      }
      if (hasScFightStartGame()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getScFightStartGame());
      }
      if (hasScFightLoadResource()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getScFightLoadResource());
      }
      if (hasScFightRemove()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, getScFightRemove());
      }
      if (hasScFightCreate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, getScFightCreate());
      }
      if (hasScFightGameOver()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, getScFightGameOver());
      }
      if (hasScFightSendKeyFrame()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, getScFightSendKeyFrame());
      }
      if (hasPingResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(14, getPingResponse());
      }
      if (hasInviteFriendResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, getInviteFriendResponse());
      }
      if (hasInviteAnswerResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(16, getInviteAnswerResponse());
      }
      if (hasScInviteAccept()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(17, getScInviteAccept());
      }
      if (hasScInviteReject()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(18, getScInviteReject());
      }
      if (hasScInviteCancel()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(19, getScInviteCancel());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage result;
      
      // Construct using com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage();
        return builder;
      }
      
      protected com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage.getDescriptor();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage getDefaultInstanceForType() {
        return com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage) {
          return mergeFrom((com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage other) {
        if (other == com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage.getDefaultInstance()) return this;
        if (other.hasLoginCheckAccountResponse()) {
          mergeLoginCheckAccountResponse(other.getLoginCheckAccountResponse());
        }
        if (other.hasLoginCreateRoleResponse()) {
          mergeLoginCreateRoleResponse(other.getLoginCreateRoleResponse());
        }
        if (other.hasLoginGetRoleDataResponse()) {
          mergeLoginGetRoleDataResponse(other.getLoginGetRoleDataResponse());
        }
        if (other.hasMatchRoleResponse()) {
          mergeMatchRoleResponse(other.getMatchRoleResponse());
        }
        if (other.hasFightReceiveHitGameControlResponse()) {
          mergeFightReceiveHitGameControlResponse(other.getFightReceiveHitGameControlResponse());
        }
        if (other.hasFightReceivePlaneGameControlResponse()) {
          mergeFightReceivePlaneGameControlResponse(other.getFightReceivePlaneGameControlResponse());
        }
        if (other.hasFightLoadCompleteResponse()) {
          mergeFightLoadCompleteResponse(other.getFightLoadCompleteResponse());
        }
        if (other.hasScFightStartGame()) {
          mergeScFightStartGame(other.getScFightStartGame());
        }
        if (other.hasScFightLoadResource()) {
          mergeScFightLoadResource(other.getScFightLoadResource());
        }
        if (other.hasScFightRemove()) {
          mergeScFightRemove(other.getScFightRemove());
        }
        if (other.hasScFightCreate()) {
          mergeScFightCreate(other.getScFightCreate());
        }
        if (other.hasScFightGameOver()) {
          mergeScFightGameOver(other.getScFightGameOver());
        }
        if (other.hasScFightSendKeyFrame()) {
          mergeScFightSendKeyFrame(other.getScFightSendKeyFrame());
        }
        if (other.hasPingResponse()) {
          mergePingResponse(other.getPingResponse());
        }
        if (other.hasInviteFriendResponse()) {
          mergeInviteFriendResponse(other.getInviteFriendResponse());
        }
        if (other.hasInviteAnswerResponse()) {
          mergeInviteAnswerResponse(other.getInviteAnswerResponse());
        }
        if (other.hasScInviteAccept()) {
          mergeScInviteAccept(other.getScInviteAccept());
        }
        if (other.hasScInviteReject()) {
          mergeScInviteReject(other.getScInviteReject());
        }
        if (other.hasScInviteCancel()) {
          mergeScInviteCancel(other.getScInviteCancel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountResponse.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountResponse.newBuilder();
              if (hasLoginCheckAccountResponse()) {
                subBuilder.mergeFrom(getLoginCheckAccountResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCheckAccountResponse(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleResponse.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleResponse.newBuilder();
              if (hasLoginCreateRoleResponse()) {
                subBuilder.mergeFrom(getLoginCreateRoleResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCreateRoleResponse(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataResponse.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataResponse.newBuilder();
              if (hasLoginGetRoleDataResponse()) {
                subBuilder.mergeFrom(getLoginGetRoleDataResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginGetRoleDataResponse(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleResponse.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleResponse.newBuilder();
              if (hasMatchRoleResponse()) {
                subBuilder.mergeFrom(getMatchRoleResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMatchRoleResponse(subBuilder.buildPartial());
              break;
            }
            case 42: {
              com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlResponse.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlResponse.newBuilder();
              if (hasFightReceiveHitGameControlResponse()) {
                subBuilder.mergeFrom(getFightReceiveHitGameControlResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFightReceiveHitGameControlResponse(subBuilder.buildPartial());
              break;
            }
            case 50: {
              com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlResponse.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlResponse.newBuilder();
              if (hasFightReceivePlaneGameControlResponse()) {
                subBuilder.mergeFrom(getFightReceivePlaneGameControlResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFightReceivePlaneGameControlResponse(subBuilder.buildPartial());
              break;
            }
            case 58: {
              com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteResponse.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteResponse.newBuilder();
              if (hasFightLoadCompleteResponse()) {
                subBuilder.mergeFrom(getFightLoadCompleteResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFightLoadCompleteResponse(subBuilder.buildPartial());
              break;
            }
            case 66: {
              com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightStartGame.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightStartGame.newBuilder();
              if (hasScFightStartGame()) {
                subBuilder.mergeFrom(getScFightStartGame());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setScFightStartGame(subBuilder.buildPartial());
              break;
            }
            case 74: {
              com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightLoadResource.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightLoadResource.newBuilder();
              if (hasScFightLoadResource()) {
                subBuilder.mergeFrom(getScFightLoadResource());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setScFightLoadResource(subBuilder.buildPartial());
              break;
            }
            case 82: {
              com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightRemove.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightRemove.newBuilder();
              if (hasScFightRemove()) {
                subBuilder.mergeFrom(getScFightRemove());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setScFightRemove(subBuilder.buildPartial());
              break;
            }
            case 90: {
              com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightCreate.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightCreate.newBuilder();
              if (hasScFightCreate()) {
                subBuilder.mergeFrom(getScFightCreate());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setScFightCreate(subBuilder.buildPartial());
              break;
            }
            case 98: {
              com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightGameOver.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightGameOver.newBuilder();
              if (hasScFightGameOver()) {
                subBuilder.mergeFrom(getScFightGameOver());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setScFightGameOver(subBuilder.buildPartial());
              break;
            }
            case 106: {
              com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightSendKeyFrame.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightSendKeyFrame.newBuilder();
              if (hasScFightSendKeyFrame()) {
                subBuilder.mergeFrom(getScFightSendKeyFrame());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setScFightSendKeyFrame(subBuilder.buildPartial());
              break;
            }
            case 114: {
              com.randioo.demo_optimisticframe_server.protocal.Ping.PingResponse.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Ping.PingResponse.newBuilder();
              if (hasPingResponse()) {
                subBuilder.mergeFrom(getPingResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPingResponse(subBuilder.buildPartial());
              break;
            }
            case 122: {
              com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse.newBuilder();
              if (hasInviteFriendResponse()) {
                subBuilder.mergeFrom(getInviteFriendResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setInviteFriendResponse(subBuilder.buildPartial());
              break;
            }
            case 130: {
              com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse.newBuilder();
              if (hasInviteAnswerResponse()) {
                subBuilder.mergeFrom(getInviteAnswerResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setInviteAnswerResponse(subBuilder.buildPartial());
              break;
            }
            case 138: {
              com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept.newBuilder();
              if (hasScInviteAccept()) {
                subBuilder.mergeFrom(getScInviteAccept());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setScInviteAccept(subBuilder.buildPartial());
              break;
            }
            case 146: {
              com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject.newBuilder();
              if (hasScInviteReject()) {
                subBuilder.mergeFrom(getScInviteReject());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setScInviteReject(subBuilder.buildPartial());
              break;
            }
            case 154: {
              com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel.Builder subBuilder = com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel.newBuilder();
              if (hasScInviteCancel()) {
                subBuilder.mergeFrom(getScInviteCancel());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setScInviteCancel(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.LoginCheckAccountResponse loginCheckAccountResponse = 1;
      public boolean hasLoginCheckAccountResponse() {
        return result.hasLoginCheckAccountResponse();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountResponse getLoginCheckAccountResponse() {
        return result.getLoginCheckAccountResponse();
      }
      public Builder setLoginCheckAccountResponse(com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCheckAccountResponse = true;
        result.loginCheckAccountResponse_ = value;
        return this;
      }
      public Builder setLoginCheckAccountResponse(com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountResponse.Builder builderForValue) {
        result.hasLoginCheckAccountResponse = true;
        result.loginCheckAccountResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCheckAccountResponse(com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountResponse value) {
        if (result.hasLoginCheckAccountResponse() &&
            result.loginCheckAccountResponse_ != com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountResponse.getDefaultInstance()) {
          result.loginCheckAccountResponse_ =
            com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountResponse.newBuilder(result.loginCheckAccountResponse_).mergeFrom(value).buildPartial();
        } else {
          result.loginCheckAccountResponse_ = value;
        }
        result.hasLoginCheckAccountResponse = true;
        return this;
      }
      public Builder clearLoginCheckAccountResponse() {
        result.hasLoginCheckAccountResponse = false;
        result.loginCheckAccountResponse_ = com.randioo.demo_optimisticframe_server.protocal.Login.LoginCheckAccountResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.LoginCreateRoleResponse loginCreateRoleResponse = 2;
      public boolean hasLoginCreateRoleResponse() {
        return result.hasLoginCreateRoleResponse();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleResponse getLoginCreateRoleResponse() {
        return result.getLoginCreateRoleResponse();
      }
      public Builder setLoginCreateRoleResponse(com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCreateRoleResponse = true;
        result.loginCreateRoleResponse_ = value;
        return this;
      }
      public Builder setLoginCreateRoleResponse(com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleResponse.Builder builderForValue) {
        result.hasLoginCreateRoleResponse = true;
        result.loginCreateRoleResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCreateRoleResponse(com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleResponse value) {
        if (result.hasLoginCreateRoleResponse() &&
            result.loginCreateRoleResponse_ != com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleResponse.getDefaultInstance()) {
          result.loginCreateRoleResponse_ =
            com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleResponse.newBuilder(result.loginCreateRoleResponse_).mergeFrom(value).buildPartial();
        } else {
          result.loginCreateRoleResponse_ = value;
        }
        result.hasLoginCreateRoleResponse = true;
        return this;
      }
      public Builder clearLoginCreateRoleResponse() {
        result.hasLoginCreateRoleResponse = false;
        result.loginCreateRoleResponse_ = com.randioo.demo_optimisticframe_server.protocal.Login.LoginCreateRoleResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.LoginGetRoleDataResponse loginGetRoleDataResponse = 3;
      public boolean hasLoginGetRoleDataResponse() {
        return result.hasLoginGetRoleDataResponse();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataResponse getLoginGetRoleDataResponse() {
        return result.getLoginGetRoleDataResponse();
      }
      public Builder setLoginGetRoleDataResponse(com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginGetRoleDataResponse = true;
        result.loginGetRoleDataResponse_ = value;
        return this;
      }
      public Builder setLoginGetRoleDataResponse(com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataResponse.Builder builderForValue) {
        result.hasLoginGetRoleDataResponse = true;
        result.loginGetRoleDataResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginGetRoleDataResponse(com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataResponse value) {
        if (result.hasLoginGetRoleDataResponse() &&
            result.loginGetRoleDataResponse_ != com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataResponse.getDefaultInstance()) {
          result.loginGetRoleDataResponse_ =
            com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataResponse.newBuilder(result.loginGetRoleDataResponse_).mergeFrom(value).buildPartial();
        } else {
          result.loginGetRoleDataResponse_ = value;
        }
        result.hasLoginGetRoleDataResponse = true;
        return this;
      }
      public Builder clearLoginGetRoleDataResponse() {
        result.hasLoginGetRoleDataResponse = false;
        result.loginGetRoleDataResponse_ = com.randioo.demo_optimisticframe_server.protocal.Login.LoginGetRoleDataResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.MatchRoleResponse matchRoleResponse = 4;
      public boolean hasMatchRoleResponse() {
        return result.hasMatchRoleResponse();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleResponse getMatchRoleResponse() {
        return result.getMatchRoleResponse();
      }
      public Builder setMatchRoleResponse(com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasMatchRoleResponse = true;
        result.matchRoleResponse_ = value;
        return this;
      }
      public Builder setMatchRoleResponse(com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleResponse.Builder builderForValue) {
        result.hasMatchRoleResponse = true;
        result.matchRoleResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeMatchRoleResponse(com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleResponse value) {
        if (result.hasMatchRoleResponse() &&
            result.matchRoleResponse_ != com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleResponse.getDefaultInstance()) {
          result.matchRoleResponse_ =
            com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleResponse.newBuilder(result.matchRoleResponse_).mergeFrom(value).buildPartial();
        } else {
          result.matchRoleResponse_ = value;
        }
        result.hasMatchRoleResponse = true;
        return this;
      }
      public Builder clearMatchRoleResponse() {
        result.hasMatchRoleResponse = false;
        result.matchRoleResponse_ = com.randioo.demo_optimisticframe_server.protocal.Match.MatchRoleResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.FightReceiveHitGameControlResponse fightReceiveHitGameControlResponse = 5;
      public boolean hasFightReceiveHitGameControlResponse() {
        return result.hasFightReceiveHitGameControlResponse();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlResponse getFightReceiveHitGameControlResponse() {
        return result.getFightReceiveHitGameControlResponse();
      }
      public Builder setFightReceiveHitGameControlResponse(com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFightReceiveHitGameControlResponse = true;
        result.fightReceiveHitGameControlResponse_ = value;
        return this;
      }
      public Builder setFightReceiveHitGameControlResponse(com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlResponse.Builder builderForValue) {
        result.hasFightReceiveHitGameControlResponse = true;
        result.fightReceiveHitGameControlResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeFightReceiveHitGameControlResponse(com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlResponse value) {
        if (result.hasFightReceiveHitGameControlResponse() &&
            result.fightReceiveHitGameControlResponse_ != com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlResponse.getDefaultInstance()) {
          result.fightReceiveHitGameControlResponse_ =
            com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlResponse.newBuilder(result.fightReceiveHitGameControlResponse_).mergeFrom(value).buildPartial();
        } else {
          result.fightReceiveHitGameControlResponse_ = value;
        }
        result.hasFightReceiveHitGameControlResponse = true;
        return this;
      }
      public Builder clearFightReceiveHitGameControlResponse() {
        result.hasFightReceiveHitGameControlResponse = false;
        result.fightReceiveHitGameControlResponse_ = com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceiveHitGameControlResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.FightReceivePlaneGameControlResponse fightReceivePlaneGameControlResponse = 6;
      public boolean hasFightReceivePlaneGameControlResponse() {
        return result.hasFightReceivePlaneGameControlResponse();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlResponse getFightReceivePlaneGameControlResponse() {
        return result.getFightReceivePlaneGameControlResponse();
      }
      public Builder setFightReceivePlaneGameControlResponse(com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFightReceivePlaneGameControlResponse = true;
        result.fightReceivePlaneGameControlResponse_ = value;
        return this;
      }
      public Builder setFightReceivePlaneGameControlResponse(com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlResponse.Builder builderForValue) {
        result.hasFightReceivePlaneGameControlResponse = true;
        result.fightReceivePlaneGameControlResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeFightReceivePlaneGameControlResponse(com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlResponse value) {
        if (result.hasFightReceivePlaneGameControlResponse() &&
            result.fightReceivePlaneGameControlResponse_ != com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlResponse.getDefaultInstance()) {
          result.fightReceivePlaneGameControlResponse_ =
            com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlResponse.newBuilder(result.fightReceivePlaneGameControlResponse_).mergeFrom(value).buildPartial();
        } else {
          result.fightReceivePlaneGameControlResponse_ = value;
        }
        result.hasFightReceivePlaneGameControlResponse = true;
        return this;
      }
      public Builder clearFightReceivePlaneGameControlResponse() {
        result.hasFightReceivePlaneGameControlResponse = false;
        result.fightReceivePlaneGameControlResponse_ = com.randioo.demo_optimisticframe_server.protocal.Fight.FightReceivePlaneGameControlResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.FightLoadCompleteResponse fightLoadCompleteResponse = 7;
      public boolean hasFightLoadCompleteResponse() {
        return result.hasFightLoadCompleteResponse();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteResponse getFightLoadCompleteResponse() {
        return result.getFightLoadCompleteResponse();
      }
      public Builder setFightLoadCompleteResponse(com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFightLoadCompleteResponse = true;
        result.fightLoadCompleteResponse_ = value;
        return this;
      }
      public Builder setFightLoadCompleteResponse(com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteResponse.Builder builderForValue) {
        result.hasFightLoadCompleteResponse = true;
        result.fightLoadCompleteResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeFightLoadCompleteResponse(com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteResponse value) {
        if (result.hasFightLoadCompleteResponse() &&
            result.fightLoadCompleteResponse_ != com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteResponse.getDefaultInstance()) {
          result.fightLoadCompleteResponse_ =
            com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteResponse.newBuilder(result.fightLoadCompleteResponse_).mergeFrom(value).buildPartial();
        } else {
          result.fightLoadCompleteResponse_ = value;
        }
        result.hasFightLoadCompleteResponse = true;
        return this;
      }
      public Builder clearFightLoadCompleteResponse() {
        result.hasFightLoadCompleteResponse = false;
        result.fightLoadCompleteResponse_ = com.randioo.demo_optimisticframe_server.protocal.Fight.FightLoadCompleteResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.SCFightStartGame scFightStartGame = 8;
      public boolean hasScFightStartGame() {
        return result.hasScFightStartGame();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightStartGame getScFightStartGame() {
        return result.getScFightStartGame();
      }
      public Builder setScFightStartGame(com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightStartGame value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasScFightStartGame = true;
        result.scFightStartGame_ = value;
        return this;
      }
      public Builder setScFightStartGame(com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightStartGame.Builder builderForValue) {
        result.hasScFightStartGame = true;
        result.scFightStartGame_ = builderForValue.build();
        return this;
      }
      public Builder mergeScFightStartGame(com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightStartGame value) {
        if (result.hasScFightStartGame() &&
            result.scFightStartGame_ != com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightStartGame.getDefaultInstance()) {
          result.scFightStartGame_ =
            com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightStartGame.newBuilder(result.scFightStartGame_).mergeFrom(value).buildPartial();
        } else {
          result.scFightStartGame_ = value;
        }
        result.hasScFightStartGame = true;
        return this;
      }
      public Builder clearScFightStartGame() {
        result.hasScFightStartGame = false;
        result.scFightStartGame_ = com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightStartGame.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.SCFightLoadResource scFightLoadResource = 9;
      public boolean hasScFightLoadResource() {
        return result.hasScFightLoadResource();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightLoadResource getScFightLoadResource() {
        return result.getScFightLoadResource();
      }
      public Builder setScFightLoadResource(com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightLoadResource value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasScFightLoadResource = true;
        result.scFightLoadResource_ = value;
        return this;
      }
      public Builder setScFightLoadResource(com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightLoadResource.Builder builderForValue) {
        result.hasScFightLoadResource = true;
        result.scFightLoadResource_ = builderForValue.build();
        return this;
      }
      public Builder mergeScFightLoadResource(com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightLoadResource value) {
        if (result.hasScFightLoadResource() &&
            result.scFightLoadResource_ != com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightLoadResource.getDefaultInstance()) {
          result.scFightLoadResource_ =
            com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightLoadResource.newBuilder(result.scFightLoadResource_).mergeFrom(value).buildPartial();
        } else {
          result.scFightLoadResource_ = value;
        }
        result.hasScFightLoadResource = true;
        return this;
      }
      public Builder clearScFightLoadResource() {
        result.hasScFightLoadResource = false;
        result.scFightLoadResource_ = com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightLoadResource.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.SCFightRemove scFightRemove = 10;
      public boolean hasScFightRemove() {
        return result.hasScFightRemove();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightRemove getScFightRemove() {
        return result.getScFightRemove();
      }
      public Builder setScFightRemove(com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightRemove value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasScFightRemove = true;
        result.scFightRemove_ = value;
        return this;
      }
      public Builder setScFightRemove(com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightRemove.Builder builderForValue) {
        result.hasScFightRemove = true;
        result.scFightRemove_ = builderForValue.build();
        return this;
      }
      public Builder mergeScFightRemove(com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightRemove value) {
        if (result.hasScFightRemove() &&
            result.scFightRemove_ != com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightRemove.getDefaultInstance()) {
          result.scFightRemove_ =
            com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightRemove.newBuilder(result.scFightRemove_).mergeFrom(value).buildPartial();
        } else {
          result.scFightRemove_ = value;
        }
        result.hasScFightRemove = true;
        return this;
      }
      public Builder clearScFightRemove() {
        result.hasScFightRemove = false;
        result.scFightRemove_ = com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightRemove.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.SCFightCreate scFightCreate = 11;
      public boolean hasScFightCreate() {
        return result.hasScFightCreate();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightCreate getScFightCreate() {
        return result.getScFightCreate();
      }
      public Builder setScFightCreate(com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightCreate value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasScFightCreate = true;
        result.scFightCreate_ = value;
        return this;
      }
      public Builder setScFightCreate(com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightCreate.Builder builderForValue) {
        result.hasScFightCreate = true;
        result.scFightCreate_ = builderForValue.build();
        return this;
      }
      public Builder mergeScFightCreate(com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightCreate value) {
        if (result.hasScFightCreate() &&
            result.scFightCreate_ != com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightCreate.getDefaultInstance()) {
          result.scFightCreate_ =
            com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightCreate.newBuilder(result.scFightCreate_).mergeFrom(value).buildPartial();
        } else {
          result.scFightCreate_ = value;
        }
        result.hasScFightCreate = true;
        return this;
      }
      public Builder clearScFightCreate() {
        result.hasScFightCreate = false;
        result.scFightCreate_ = com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightCreate.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.SCFightGameOver scFightGameOver = 12;
      public boolean hasScFightGameOver() {
        return result.hasScFightGameOver();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightGameOver getScFightGameOver() {
        return result.getScFightGameOver();
      }
      public Builder setScFightGameOver(com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightGameOver value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasScFightGameOver = true;
        result.scFightGameOver_ = value;
        return this;
      }
      public Builder setScFightGameOver(com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightGameOver.Builder builderForValue) {
        result.hasScFightGameOver = true;
        result.scFightGameOver_ = builderForValue.build();
        return this;
      }
      public Builder mergeScFightGameOver(com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightGameOver value) {
        if (result.hasScFightGameOver() &&
            result.scFightGameOver_ != com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightGameOver.getDefaultInstance()) {
          result.scFightGameOver_ =
            com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightGameOver.newBuilder(result.scFightGameOver_).mergeFrom(value).buildPartial();
        } else {
          result.scFightGameOver_ = value;
        }
        result.hasScFightGameOver = true;
        return this;
      }
      public Builder clearScFightGameOver() {
        result.hasScFightGameOver = false;
        result.scFightGameOver_ = com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightGameOver.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.SCFightSendKeyFrame scFightSendKeyFrame = 13;
      public boolean hasScFightSendKeyFrame() {
        return result.hasScFightSendKeyFrame();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightSendKeyFrame getScFightSendKeyFrame() {
        return result.getScFightSendKeyFrame();
      }
      public Builder setScFightSendKeyFrame(com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightSendKeyFrame value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasScFightSendKeyFrame = true;
        result.scFightSendKeyFrame_ = value;
        return this;
      }
      public Builder setScFightSendKeyFrame(com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightSendKeyFrame.Builder builderForValue) {
        result.hasScFightSendKeyFrame = true;
        result.scFightSendKeyFrame_ = builderForValue.build();
        return this;
      }
      public Builder mergeScFightSendKeyFrame(com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightSendKeyFrame value) {
        if (result.hasScFightSendKeyFrame() &&
            result.scFightSendKeyFrame_ != com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightSendKeyFrame.getDefaultInstance()) {
          result.scFightSendKeyFrame_ =
            com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightSendKeyFrame.newBuilder(result.scFightSendKeyFrame_).mergeFrom(value).buildPartial();
        } else {
          result.scFightSendKeyFrame_ = value;
        }
        result.hasScFightSendKeyFrame = true;
        return this;
      }
      public Builder clearScFightSendKeyFrame() {
        result.hasScFightSendKeyFrame = false;
        result.scFightSendKeyFrame_ = com.randioo.demo_optimisticframe_server.protocal.Fight.SCFightSendKeyFrame.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.PingResponse pingResponse = 14;
      public boolean hasPingResponse() {
        return result.hasPingResponse();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Ping.PingResponse getPingResponse() {
        return result.getPingResponse();
      }
      public Builder setPingResponse(com.randioo.demo_optimisticframe_server.protocal.Ping.PingResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPingResponse = true;
        result.pingResponse_ = value;
        return this;
      }
      public Builder setPingResponse(com.randioo.demo_optimisticframe_server.protocal.Ping.PingResponse.Builder builderForValue) {
        result.hasPingResponse = true;
        result.pingResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergePingResponse(com.randioo.demo_optimisticframe_server.protocal.Ping.PingResponse value) {
        if (result.hasPingResponse() &&
            result.pingResponse_ != com.randioo.demo_optimisticframe_server.protocal.Ping.PingResponse.getDefaultInstance()) {
          result.pingResponse_ =
            com.randioo.demo_optimisticframe_server.protocal.Ping.PingResponse.newBuilder(result.pingResponse_).mergeFrom(value).buildPartial();
        } else {
          result.pingResponse_ = value;
        }
        result.hasPingResponse = true;
        return this;
      }
      public Builder clearPingResponse() {
        result.hasPingResponse = false;
        result.pingResponse_ = com.randioo.demo_optimisticframe_server.protocal.Ping.PingResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.InviteFriendResponse inviteFriendResponse = 15;
      public boolean hasInviteFriendResponse() {
        return result.hasInviteFriendResponse();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse getInviteFriendResponse() {
        return result.getInviteFriendResponse();
      }
      public Builder setInviteFriendResponse(com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasInviteFriendResponse = true;
        result.inviteFriendResponse_ = value;
        return this;
      }
      public Builder setInviteFriendResponse(com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse.Builder builderForValue) {
        result.hasInviteFriendResponse = true;
        result.inviteFriendResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeInviteFriendResponse(com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse value) {
        if (result.hasInviteFriendResponse() &&
            result.inviteFriendResponse_ != com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse.getDefaultInstance()) {
          result.inviteFriendResponse_ =
            com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse.newBuilder(result.inviteFriendResponse_).mergeFrom(value).buildPartial();
        } else {
          result.inviteFriendResponse_ = value;
        }
        result.hasInviteFriendResponse = true;
        return this;
      }
      public Builder clearInviteFriendResponse() {
        result.hasInviteFriendResponse = false;
        result.inviteFriendResponse_ = com.randioo.demo_optimisticframe_server.protocal.Invite.InviteFriendResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.InviteAnswerResponse inviteAnswerResponse = 16;
      public boolean hasInviteAnswerResponse() {
        return result.hasInviteAnswerResponse();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse getInviteAnswerResponse() {
        return result.getInviteAnswerResponse();
      }
      public Builder setInviteAnswerResponse(com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasInviteAnswerResponse = true;
        result.inviteAnswerResponse_ = value;
        return this;
      }
      public Builder setInviteAnswerResponse(com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse.Builder builderForValue) {
        result.hasInviteAnswerResponse = true;
        result.inviteAnswerResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeInviteAnswerResponse(com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse value) {
        if (result.hasInviteAnswerResponse() &&
            result.inviteAnswerResponse_ != com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse.getDefaultInstance()) {
          result.inviteAnswerResponse_ =
            com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse.newBuilder(result.inviteAnswerResponse_).mergeFrom(value).buildPartial();
        } else {
          result.inviteAnswerResponse_ = value;
        }
        result.hasInviteAnswerResponse = true;
        return this;
      }
      public Builder clearInviteAnswerResponse() {
        result.hasInviteAnswerResponse = false;
        result.inviteAnswerResponse_ = com.randioo.demo_optimisticframe_server.protocal.Invite.InviteAnswerResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.SCInviteAccept scInviteAccept = 17;
      public boolean hasScInviteAccept() {
        return result.hasScInviteAccept();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept getScInviteAccept() {
        return result.getScInviteAccept();
      }
      public Builder setScInviteAccept(com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasScInviteAccept = true;
        result.scInviteAccept_ = value;
        return this;
      }
      public Builder setScInviteAccept(com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept.Builder builderForValue) {
        result.hasScInviteAccept = true;
        result.scInviteAccept_ = builderForValue.build();
        return this;
      }
      public Builder mergeScInviteAccept(com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept value) {
        if (result.hasScInviteAccept() &&
            result.scInviteAccept_ != com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept.getDefaultInstance()) {
          result.scInviteAccept_ =
            com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept.newBuilder(result.scInviteAccept_).mergeFrom(value).buildPartial();
        } else {
          result.scInviteAccept_ = value;
        }
        result.hasScInviteAccept = true;
        return this;
      }
      public Builder clearScInviteAccept() {
        result.hasScInviteAccept = false;
        result.scInviteAccept_ = com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteAccept.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.SCInviteReject scInviteReject = 18;
      public boolean hasScInviteReject() {
        return result.hasScInviteReject();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject getScInviteReject() {
        return result.getScInviteReject();
      }
      public Builder setScInviteReject(com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasScInviteReject = true;
        result.scInviteReject_ = value;
        return this;
      }
      public Builder setScInviteReject(com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject.Builder builderForValue) {
        result.hasScInviteReject = true;
        result.scInviteReject_ = builderForValue.build();
        return this;
      }
      public Builder mergeScInviteReject(com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject value) {
        if (result.hasScInviteReject() &&
            result.scInviteReject_ != com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject.getDefaultInstance()) {
          result.scInviteReject_ =
            com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject.newBuilder(result.scInviteReject_).mergeFrom(value).buildPartial();
        } else {
          result.scInviteReject_ = value;
        }
        result.hasScInviteReject = true;
        return this;
      }
      public Builder clearScInviteReject() {
        result.hasScInviteReject = false;
        result.scInviteReject_ = com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteReject.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.demo_optimisticframe_server.protocal.SCInviteCancel scInviteCancel = 19;
      public boolean hasScInviteCancel() {
        return result.hasScInviteCancel();
      }
      public com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel getScInviteCancel() {
        return result.getScInviteCancel();
      }
      public Builder setScInviteCancel(com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasScInviteCancel = true;
        result.scInviteCancel_ = value;
        return this;
      }
      public Builder setScInviteCancel(com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel.Builder builderForValue) {
        result.hasScInviteCancel = true;
        result.scInviteCancel_ = builderForValue.build();
        return this;
      }
      public Builder mergeScInviteCancel(com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel value) {
        if (result.hasScInviteCancel() &&
            result.scInviteCancel_ != com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel.getDefaultInstance()) {
          result.scInviteCancel_ =
            com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel.newBuilder(result.scInviteCancel_).mergeFrom(value).buildPartial();
        } else {
          result.scInviteCancel_ = value;
        }
        result.hasScInviteCancel = true;
        return this;
      }
      public Builder clearScInviteCancel() {
        result.hasScInviteCancel = false;
        result.scInviteCancel_ = com.randioo.demo_optimisticframe_server.protocal.Invite.SCInviteCancel.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.demo_optimisticframe_server.protocal.SCMessage)
    }
    
    static {
      defaultInstance = new SCMessage(true);
      com.randioo.demo_optimisticframe_server.protocal.ServerMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.demo_optimisticframe_server.protocal.SCMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_demo_optimisticframe_server_protocal_SCMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_demo_optimisticframe_server_protocal_SCMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ServerMessage.proto\0220com.randioo.demo_" +
      "optimisticframe_server.protocal\032\013Login.p" +
      "roto\032\013Match.proto\032\013Fight.proto\032\nPing.pro" +
      "to\032\014Invite.proto\"\221\017\n\tSCMessage\022n\n\031loginC" +
      "heckAccountResponse\030\001 \001(\0132K.com.randioo." +
      "demo_optimisticframe_server.protocal.Log" +
      "inCheckAccountResponse\022j\n\027loginCreateRol" +
      "eResponse\030\002 \001(\0132I.com.randioo.demo_optim" +
      "isticframe_server.protocal.LoginCreateRo" +
      "leResponse\022l\n\030loginGetRoleDataResponse\030\003",
      " \001(\0132J.com.randioo.demo_optimisticframe_" +
      "server.protocal.LoginGetRoleDataResponse" +
      "\022^\n\021matchRoleResponse\030\004 \001(\0132C.com.randio" +
      "o.demo_optimisticframe_server.protocal.M" +
      "atchRoleResponse\022\200\001\n\"fightReceiveHitGame" +
      "ControlResponse\030\005 \001(\0132T.com.randioo.demo" +
      "_optimisticframe_server.protocal.FightRe" +
      "ceiveHitGameControlResponse\022\204\001\n$fightRec" +
      "eivePlaneGameControlResponse\030\006 \001(\0132V.com" +
      ".randioo.demo_optimisticframe_server.pro",
      "tocal.FightReceivePlaneGameControlRespon" +
      "se\022n\n\031fightLoadCompleteResponse\030\007 \001(\0132K." +
      "com.randioo.demo_optimisticframe_server." +
      "protocal.FightLoadCompleteResponse\022\\\n\020sc" +
      "FightStartGame\030\010 \001(\0132B.com.randioo.demo_" +
      "optimisticframe_server.protocal.SCFightS" +
      "tartGame\022b\n\023scFightLoadResource\030\t \001(\0132E." +
      "com.randioo.demo_optimisticframe_server." +
      "protocal.SCFightLoadResource\022V\n\rscFightR" +
      "emove\030\n \001(\0132?.com.randioo.demo_optimisti",
      "cframe_server.protocal.SCFightRemove\022V\n\r" +
      "scFightCreate\030\013 \001(\0132?.com.randioo.demo_o" +
      "ptimisticframe_server.protocal.SCFightCr" +
      "eate\022Z\n\017scFightGameOver\030\014 \001(\0132A.com.rand" +
      "ioo.demo_optimisticframe_server.protocal" +
      ".SCFightGameOver\022b\n\023scFightSendKeyFrame\030" +
      "\r \001(\0132E.com.randioo.demo_optimisticframe" +
      "_server.protocal.SCFightSendKeyFrame\022T\n\014" +
      "pingResponse\030\016 \001(\0132>.com.randioo.demo_op" +
      "timisticframe_server.protocal.PingRespon",
      "se\022d\n\024inviteFriendResponse\030\017 \001(\0132F.com.r" +
      "andioo.demo_optimisticframe_server.proto" +
      "cal.InviteFriendResponse\022d\n\024inviteAnswer" +
      "Response\030\020 \001(\0132F.com.randioo.demo_optimi" +
      "sticframe_server.protocal.InviteAnswerRe" +
      "sponse\022X\n\016scInviteAccept\030\021 \001(\0132@.com.ran" +
      "dioo.demo_optimisticframe_server.protoca" +
      "l.SCInviteAccept\022X\n\016scInviteReject\030\022 \001(\013" +
      "2@.com.randioo.demo_optimisticframe_serv" +
      "er.protocal.SCInviteReject\022X\n\016scInviteCa",
      "ncel\030\023 \001(\0132@.com.randioo.demo_optimistic" +
      "frame_server.protocal.SCInviteCancel"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_demo_optimisticframe_server_protocal_SCMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_demo_optimisticframe_server_protocal_SCMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_demo_optimisticframe_server_protocal_SCMessage_descriptor,
              new java.lang.String[] { "LoginCheckAccountResponse", "LoginCreateRoleResponse", "LoginGetRoleDataResponse", "MatchRoleResponse", "FightReceiveHitGameControlResponse", "FightReceivePlaneGameControlResponse", "FightLoadCompleteResponse", "ScFightStartGame", "ScFightLoadResource", "ScFightRemove", "ScFightCreate", "ScFightGameOver", "ScFightSendKeyFrame", "PingResponse", "InviteFriendResponse", "InviteAnswerResponse", "ScInviteAccept", "ScInviteReject", "ScInviteCancel", },
              com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage.class,
              com.randioo.demo_optimisticframe_server.protocal.ServerMessage.SCMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.demo_optimisticframe_server.protocal.Login.getDescriptor(),
          com.randioo.demo_optimisticframe_server.protocal.Match.getDescriptor(),
          com.randioo.demo_optimisticframe_server.protocal.Fight.getDescriptor(),
          com.randioo.demo_optimisticframe_server.protocal.Ping.getDescriptor(),
          com.randioo.demo_optimisticframe_server.protocal.Invite.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
